
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-30T04:38:19-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "2773fcf7fbe7ac45d41254c6391a766b96b75556",
 "version": "0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
