schema = {
    "name": "tyb",
    "type": "record",
    "fields": [
        {"start":   0, "end":   2, "type": "string", "name": "place_id"},
        {"start":   2, "end":   4, "type": "string", "name": "year"},
        {"start":   4, "end":   5, "type": "string", "name": "kai"},
        {"start":   5, "end":   6, "type": "string", "name": "nichi"},
        {"start":   6, "end":   8, "type": "string", "name": "number_of_race"},
        {"start":   8, "end":  10, "type": "string", "name": "pp"},
        {"start":  10, "end":  15, "type": "string", "name": "idm"},
        {"start":  15, "end":  20, "type": "string", "name": "jockey_score"},
        {"start":  20, "end":  25, "type": "string", "name": "info_score"},
        {"start":  25, "end":  30, "type": "string", "name": "odds_score"},
        {"start":  30, "end":  35, "type": "string", "name": "paddock_score"},
        {"start":  40, "end":  45, "type": "string", "name": "total_score"},
        {"start":  45, "end":  46, "type": "string", "name": "harness_change_info"},
        {"start":  46, "end":  47, "type": "string", "name": "foot_info"},
        {"start":  47, "end":  48, "type": "string", "name": "cancel_flag"},
        {"start":  48, "end":  53, "type": "string", "name": "jockey_id"},
        {"start":  53, "end":  65, "type": "string", "name": "jockey_name"},
        {"start":  65, "end":  68, "type": "string", "name": "jockey_weight"},
        {"start":  68, "end":  69, "type": "string", "name": "apprentice_id"},
        {"start":  69, "end":  71, "type": "string", "name": "track_cond_id"},
        {"start":  71, "end":  72, "type": "string", "name": "weather_id"},
        {"start":  72, "end":  78, "type": "string", "name": "win_odds"},
        {"start":  78, "end":  84, "type": "string", "name": "show_odds"},
        {"start":  84, "end":  88, "type": "string", "name": "hhmm_at_get_odds"},
        {"start":  88, "end":  91, "type": "string", "name": "horse_weight"},
        {"start":  91, "end":  94, "type": "string", "name": "horse_weight_diff"},
        {"start":  94, "end":  95, "type": "string", "name": "odds_mark_id"},
        {"start":  95, "end":  96, "type": "string", "name": "paddock_mark_id"},
        {"start":  96, "end":  97, "type": "string", "name": "total_mark_id"}
    ]
}
