#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['tcsamcli']

package_data = \
{'': ['*'], 'tcsamcli': ['templates/*']}

install_requires = \
['jinja2', 'aws-sam-cli==0.17.0', 'click~=6.7', 'sh', 'toml', 'tclambda']

entry_points = \
{'console_scripts': ['tc-sam = tcsamcli.__main__:cli']}

setup(name='tc-sam-cli',
      version='0.0.7',
      description='Tc sam cli',
      author='Niels Lemmens',
      author_email='draso.odin@gmail.com',
      url=None,
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      entry_points=entry_points,
      python_requires='>=3.7',
     )
