
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-06-16T12:34:07+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "6ea5076626d457c4780f37462f00d8dd0f6ebb42",
 "version": "0.0.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
