
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-06-15T17:56:18+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "4656160929c51b3d0125876fd851d399bdbf724f",
 "version": "0.0.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
