
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-06-02T21:23:12-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "033a871bcec73ad09e769c02b90063f47aa2a4bd",
 "version": "2.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
