language: python

python:
  - 3.6

env:
  - TOXENV=py,codecov-travis CC=gcc-6 CXX=g++-6
  - TOXENV=py-pythran,codecov-travis CC=clang CXX=clang++

before_cache:
  - |
      coverage erase
      rm -f $HOME/.cache/pip/log/debug.log

cache:
    directories:
        - $HOME/.cache/pip
        - $TRAVIS_BUILD_DIR/.tox

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-6
            - g++-6
            - libfftw3-dev
            - libhdf5-openmpi-dev
            - openmpi-bin
            - libopenblas-dev

install:
    - pip install -U pip setuptools wheel six colorlog
    - pip install -U tox coverage pytest pytest-qt
    - pip install -U numpy

before_script:
    - |
      mkdir -p $HOME/.config/matplotlib
      echo 'backend      : agg' > $HOME/.config/matplotlib/matplotlibrc
      echo -e "[pythran]\ncomplex_hook=True\n\n[compiler]\nCXX = clang++\nCC = clang\n" > $HOME/.pythranrc

script:
    - tox -vv

after_failure:
    - cat $TRAVIS_BUILD_DIR/.tox/log/*.log

notifications:
  email: false
  irc: "chat.freenode.net#fluiddyn-dev"
