repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: flake8
-   repo: git://github.com/FalconSocial/pre-commit-mirrors-pep257
    sha: 'f464d46624a959c6969ce6bcf2cd531cdeefb85a'
    hooks:
    -   id: pep257
