apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ./../base

resources:
  - ingress.yaml

namespace: {{ project_name }}-prod

commonLabels:
  app.kubernetes.io/part-of: {{ project_name }}

secretGenerator:
  - name: {{ project_name }}-secrets
    behavior: replace
    env: prod.env

vars:
  - name: NAMESPACE_URL
    objref:
      kind: Ingress
      name: {{ project_name }}-ingress
      apiVersion: extensions/v1beta1
    fieldref:
      fieldpath: metadata.namespace

