---
language: python

# Build only commits on master and release tags for the "Build pushed branches" feature.
# This prevents building twice on PRs originating from our repo ("Build pushed pull requests)".
# See:
#   - https://github.com/travis-ci/travis-ci/issues/1147
#   - https://docs.travis-ci.com/user/pull-requests/#double-builds-on-pull-requests
branches:
  only:
    - master
    - /v[0-9]+\.[0-9]+\.[0-9]+(-.*)?$/

cache:
  - pip
  - directories:
      - "node_modules"
      - $HOME/.cache
os:
  - linux
before_install:
  - nvm install $TRAVIS_NODE_VERSION
  - which tox >/dev/null || if [ -z ${VIRTUAL_ENV+x} ]; then python -m pip install --user tox tox-pyenv wheel ; else python -m pip install tox tox-pyenv wheel twine; fi
jobs:
  include:
    - script:
        # package building added here purely to fail-fast if is broken
        - python setup.py sdist bdist_wheel
        - travis_wait python -m tox
      env: TOXENV=lint,py27,molecule
      python: "2.7"
      language: nodejs
      node_js:
        - "8"
      services:
        - docker
    - script: python -m tox
      python: "3.4"
      env: TOXENV=py34
    - script: python -m tox
      python: "3.5"
      env: TOXENV=py35
    - script: python -m tox
      python: "3.6"
      env: TOXENV=py36 PYTHON='3.6' PYENV_VERSION='system'
    - script: python -m pip install -q tox-travis && python -m tox
      python: "3.7"
      env: TOXENV=py37 PYTHON='3.7'
      # begin: workaround to enable support for py37: https://github.com/travis-ci/travis-ci/issues/9815
      dist: xenial
      sudo: required
      # end
env:
  global:
    - PIP_DISABLE_PIP_VERSION_CHECK=1
    - TRAVIS_NODE_VERSION="v8.11.3"
