name: fwdpy_docs

channels:
    - defaults
    - conda-forge
    - bioconda

dependencies:
    - python>=3.5.2
    - sphinx_rtd_theme==0.1.9
    - pybind11==2.2.3
    - gsl==2.4
    - msprime
    - openblas
    - numpy
    - pandas
    - matplotlib
    - ipython
    - cmake
    - pip:
        - cppimport
