
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-28T10:11:41-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "6ee7d48eefa2140cdb99085704e2e2535be203b4",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
