
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-06-10T11:38:19+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "fa48b246acf4fdfad50cb7433b17ed66cab3baa6",
 "version": "0.2.1b1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
