
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-06-01T20:27:06-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "6ce1d3378874388bd6c6477eda8f672317cc37e3",
 "version": "0.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
