[tool.poetry]
name = "hume"
version = "0.3.14b"
description = "really simple profiling for mere mortals"
authors = ["Shibel K. Mansour <hi@shibel.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/SHxKM/hume"
repository = "https://github.com/SHxKM/hume"
documentation = "https://github.com/SHxKM/hume/blob/master/README.md"
keywords = ["profiling", "profile", "timing"]


include = [
    "docs/console_demo.png"
]

classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "License :: OSI Approved :: MIT License",
        "Topic :: Utilities",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: Software Development :: Quality Assurance",
]


# Requirements
[tool.poetry.dependencies]
python = "^3.6"
sty = {version = "^1.0-beta.1",allows-prereleases = true}


[tool.poetry.dev-dependencies]
pytest = "^4.5"
pytest-cov = "^2.7"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
