# coding: utf-8

"""
    Pulp 3 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v3
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pulpcore.client.pulp_ansible
from pulpcore.client.pulp_ansible.api.pulp_ansible_api import PulpAnsibleApi  # noqa: E501
from pulpcore.client.pulp_ansible.rest import ApiException


class TestPulpAnsibleApi(unittest.TestCase):
    """PulpAnsibleApi unit test stubs"""

    def setUp(self):
        self.api = pulpcore.client.pulp_ansible.api.pulp_ansible_api.PulpAnsibleApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_pulp_ansible_galaxy_api_list(self):
        """Test case for pulp_ansible_galaxy_api_list

        """
        pass

    def test_pulp_ansible_galaxy_api_v1_roles_list(self):
        """Test case for pulp_ansible_galaxy_api_v1_roles_list

        """
        pass

    def test_pulp_ansible_galaxy_api_v1_roles_versions_list(self):
        """Test case for pulp_ansible_galaxy_api_v1_roles_versions_list

        """
        pass

    def test_pulp_ansible_galaxy_api_v2_collections_create(self):
        """Test case for pulp_ansible_galaxy_api_v2_collections_create

        """
        pass

    def test_pulp_ansible_galaxy_api_v2_collections_read(self):
        """Test case for pulp_ansible_galaxy_api_v2_collections_read

        """
        pass

    def test_pulp_ansible_galaxy_api_v2_collections_versions_list(self):
        """Test case for pulp_ansible_galaxy_api_v2_collections_versions_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
