PCMP_HEAD_VALUE = 5

# 头部字段位置
PCMP_MSG_TYPE_POS = 0
PCMP_MSG_BODY_POS = 1

# 消息类型
PCMP_MSG_TYPE_REQUEST_SLAVE_ROUTER = 0x88
PCMP_MSG_TYPE_ASSIGN_SLAVE_ROUTER = 0x89
PCMP_MSG_TYPE_CONNECT_PARENT_ROUTER = 0x8A
PCMP_MSG_TYPE_ACK_CONNECT_PARENT_ROUTER = 0x8B
