PNLV1_VER = 1

# 头部字段位置
PNLV1_VER_POS = 0
PNLV1_INDEX_POS = 1
PNLV1_PLAYLOAD_LEN_POS = 2
PNLV1_NEXT_HEAD_POS = 4
PNLV1_HOPS_LIMIT_POS = 5
PNLV1_HOPS_SRC_ADDR_POS = 6
PNLV1_HOPS_DST_ADDR_POS = 14

# 头部长度
PNLV1_HEAD_LEN = 22
