dist: xenial
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - travis_retry pip install -U tox-travis
script:
  - tox
notifications:
  irc:
    - "irc.freenode.org#bsdploy"
  on_success: change
  on_failure: change
