
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-29T23:30:29-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "d905a53c2030956d2aabb1cd1f8c383a9a324217",
 "version": "0.3.31"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
