[tool.poetry]
name = "marshmallow-muffin"
version = "3.0.1"
description = "Marshmallow Muffin"
authors = ["Alex Sansone <alex.sansone@cybergrx.com>", "CyberGRX Engineering Team <engineers@cybergrx.com>"]
license = "MIT"
readme = "README.rst"
editable = false
repository = "https://github.com/CyberGRX/marshmallow"
keywords = ["marshmallow", "orm", "model", "models", "python"]
exclude = ["venv", "env", "dist", "build", "tests", "tests.*"]
packages = [
    {include = "marshmallow"}
]

[tool.poetry.dependencies]
python = "^3.7"
simplejson = "^3.16.0"
pytz = "^2019.1"

[tool.poetry.dev-dependencies]
pytest = "^4.4"
pytest-cov = "^2.6"
pytest-mock = "^1.10"
coverage = "^4.5"
coveralls = "^1.7"

[tool.poetry.extras]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
