# Generated by Django 2.1.8 on 2019-04-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleboxdjango', '0002_auto_20190411_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='boolean_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='boolean_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='boolean_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='boolean_4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='boolean_5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='boolean_6',
            field=models.BooleanField(default=False),
        ),
    ]
