jobs:

- template: azure-template.yml
  parameters:
    name: Linux
    os: linux
    tox_pre: DISPLAY=:99.0
    tox_test_env: imagetest

- template: azure-template.yml
  parameters:
    name: MacOSX
    os: macosx

- template: azure-template.yml
  parameters:
    name: Windows
    os: windows
