
[tool.poetry]
name = "py_hierarchy_2_2d"
version = "0.1"
description = ""
authors = ["joefromct", "https://github.com/joefromct/py-hierarchy-utils"]

[tool.poetry.dependencies]
python = "^3.6"
xmltodict = "^0.12.0"

[tool.poetry.dev-dependencies]
ipython = "^7.5"
tabulate = "^0.8.3"
pytest = "^4.6"
toml = "^0.10.0"
