# Generated by Django 2.1.8 on 2019-04-25 02:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saleboxdjango', '0006_auto_20190423_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='i18n',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='i18n',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='i18n',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
