# Generated by Django 2.1.8 on 2019-05-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleboxdjango', '0008_auto_20190425_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutstore',
            name='status',
            field=models.IntegerField(choices=[(10, 'New: Pending send to gateway'), (20, 'Pending: Awaiting gateway response'), (30, 'Success: Pending POST to Salebox'), (31, 'Success: Successfully POSTed to Salebox'), (40, 'Rejected: Gateway rejected payment'), (50, 'Timeout: Gateway did not respond in an acceptable time period')]),
        ),
        migrations.AlterField(
            model_name='checkoutstoreupdate',
            name='status',
            field=models.IntegerField(choices=[(10, 'New: Pending send to gateway'), (20, 'Pending: Awaiting gateway response'), (30, 'Success: Pending POST to Salebox'), (31, 'Success: Successfully POSTed to Salebox'), (40, 'Rejected: Gateway rejected payment'), (50, 'Timeout: Gateway did not respond in an acceptable time period')]),
        ),
    ]
