
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-31T18:13:12-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "80985f2a5dd5897731ad95fe91bc69ccbeb17f03",
 "version": "0.6.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
