# Generated by Django 2.2.1 on 2019-05-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script_pattern', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptblock',
            name='allowed',
            field=models.ManyToManyField(blank=True, help_text='The URLs which are allowed to include script block.', related_name='allowed', to='script_pattern.ScriptUrl', verbose_name='Allowed'),
        ),
        migrations.AlterField(
            model_name='scriptblock',
            name='disallowed',
            field=models.ManyToManyField(blank=True, help_text='The URLs which are not allowed to include script block.', related_name='disallowed', to='script_pattern.ScriptUrl', verbose_name='Disallowed'),
        ),
        migrations.AlterField(
            model_name='scripturl',
            name='pattern',
            field=models.CharField(help_text="Case-sensitive. A missing trailing slash does also match to files which start with the name of the pattern, e.g., '/admin' matches '/admin.html' too. Also pattern allow an asterisk (*) as a wildcard and a dollar sign ($) to match the end of the URL, e.g., '/*.jpg$'.", max_length=450, verbose_name='Pattern'),
        ),
    ]
