
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-06-03T12:15:06+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "bf0f21df700fd0fba75dee97c3a9a7adfba95e66",
 "version": "0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
