# -*- coding: utf-8 -*-

import scrapy


class BotItem(scrapy.Item):
    unique_control = scrapy.Field()
    organization = scrapy.Field()
    document = scrapy.Field()
    departament = scrapy.Field()
    process_number = scrapy.Field()
    ticket_id = scrapy.Field()
    ticket_number = scrapy.Field()
    ticket_creation_date = scrapy.Field()
    ticket_type_code = scrapy.Field()
    ticket_status = scrapy.Field()
    ticket_due_date_current = scrapy.Field()
    ticket_description = scrapy.Field()
    ticket_isAbleToAppeal = scrapy.Field()
    ticket_isPaid = scrapy.Field()
    ticket_location_city = scrapy.Field()
    ticket_location_description = scrapy.Field()
    ticket_severity = scrapy.Field()
    ticket_value_original = scrapy.Field()
    ticket_number_cr = scrapy.Field()
    ticket_number_da = scrapy.Field()
    ticket_value_updated = scrapy.Field()
    vehicle_plate = scrapy.Field()
    vehicle_plate_uf = scrapy.Field()
    person = scrapy.Field()
    person_document = scrapy.Field()
    imported = scrapy.Field()
    s3_directory = scrapy.Field()
    file_urls = scrapy.Field()
    files = scrapy.Field()
