
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "e1c53a18bb88b6913602e36f8e93bdd25509833e",
 "version": "2151"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
