
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-06-04T14:18:27-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "68cb2d8a5b4c859d089522a667ccf03cecf3a408",
 "version": "1.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
