---
- name: Waiting for nova-compute service up
  command: >
    docker exec kolla_toolbox openstack
    --os-interface internal
    --os-auth-url {{ keystone_admin_url }}
    --os-identity-api-version 3
    --os-project-domain-name {{ openstack_auth.domain_name }}
    --os-tenant-name {{ openstack_auth.project_name }}
    --os-username {{ openstack_auth.username }}
    --os-password {{ keystone_admin_password }}
    --os-user-domain-name {{ openstack_auth.domain_name }}
    compute service list -f json --service nova-compute
  register: nova_compute_services
  changed_when: false
  run_once: True
  delegate_to: "{{ groups['nova-api'][0] }}"
  retries: 20
  delay: 10
  until:
    - nova_compute_services | success
    - nova_compute_services.stdout | from_json | length != 0

- name: Discovering nova hosts
  command: >
    docker exec nova_api nova-manage cell_v2 discover_hosts --by-service
  register: discover_hosts
  changed_when: False
  run_once: True
  delegate_to: "{{ groups['nova-api'][0] }}"
