# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (3, 0, 0):
    new_instancemethod = lambda func, inst, cls: _itkHigherOrderAccurateDerivativeImageFilterPython.SWIG_PyInstanceMethod_New(func)
else:
    from new import instancemethod as new_instancemethod
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_itkHigherOrderAccurateDerivativeImageFilterPython', [dirname(__file__)])
        except ImportError:
            import _itkHigherOrderAccurateDerivativeImageFilterPython
            return _itkHigherOrderAccurateDerivativeImageFilterPython
        if fp is not None:
            try:
                _mod = imp.load_module('_itkHigherOrderAccurateDerivativeImageFilterPython', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _itkHigherOrderAccurateDerivativeImageFilterPython = swig_import_helper()
    del swig_import_helper
else:
    import _itkHigherOrderAccurateDerivativeImageFilterPython
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



def _swig_setattr_nondynamic_method(set):
    def set_attr(self, name, value):
        if (name == "thisown"):
            return self.this.own(value)
        if hasattr(self, name) or (name == "this"):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr


import itkImageToImageFilterAPython
import itkImageToImageFilterCommonPython
import pyBasePython
import ITKCommonBasePython
import itkImagePython
import itkIndexPython
import itkSizePython
import itkOffsetPython
import itkVectorPython
import vnl_vector_refPython
import stdcomplexPython
import vnl_vectorPython
import vnl_matrixPython
import itkFixedArrayPython
import itkRGBAPixelPython
import itkSymmetricSecondRankTensorPython
import itkMatrixPython
import itkCovariantVectorPython
import itkPointPython
import vnl_matrix_fixedPython
import itkImageRegionPython
import itkRGBPixelPython
import itkVectorImagePython
import itkVariableLengthVectorPython
import itkImageSourcePython
import itkImageSourceCommonPython

def itkHigherOrderAccurateDerivativeImageFilterIF3IF3_New():
  return itkHigherOrderAccurateDerivativeImageFilterIF3IF3.New()


def itkHigherOrderAccurateDerivativeImageFilterIF2IF2_New():
  return itkHigherOrderAccurateDerivativeImageFilterIF2IF2.New()

class itkHigherOrderAccurateDerivativeImageFilterIF2IF2(itkImageToImageFilterAPython.itkImageToImageFilterIF2IF2):
    """Proxy of C++ itkHigherOrderAccurateDerivativeImageFilterIF2IF2 class."""

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "itkHigherOrderAccurateDerivativeImageFilterIF2IF2_Pointer":
        """__New_orig__() -> itkHigherOrderAccurateDerivativeImageFilterIF2IF2_Pointer"""
        return _itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF2IF2___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "itkHigherOrderAccurateDerivativeImageFilterIF2IF2_Pointer":
        """Clone(itkHigherOrderAccurateDerivativeImageFilterIF2IF2 self) -> itkHigherOrderAccurateDerivativeImageFilterIF2IF2_Pointer"""
        return _itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF2IF2_Clone(self)

    SignedOutputPixelType = _itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF2IF2_SignedOutputPixelType

    def SetOrder(self, _arg: 'unsigned int const') -> "void":
        """SetOrder(itkHigherOrderAccurateDerivativeImageFilterIF2IF2 self, unsigned int const _arg)"""
        return _itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF2IF2_SetOrder(self, _arg)


    def GetOrder(self) -> "unsigned int":
        """GetOrder(itkHigherOrderAccurateDerivativeImageFilterIF2IF2 self) -> unsigned int"""
        return _itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF2IF2_GetOrder(self)


    def SetOrderOfAccuracy(self, _arg: 'unsigned int const') -> "void":
        """SetOrderOfAccuracy(itkHigherOrderAccurateDerivativeImageFilterIF2IF2 self, unsigned int const _arg)"""
        return _itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF2IF2_SetOrderOfAccuracy(self, _arg)


    def GetOrderOfAccuracy(self) -> "unsigned int":
        """GetOrderOfAccuracy(itkHigherOrderAccurateDerivativeImageFilterIF2IF2 self) -> unsigned int"""
        return _itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF2IF2_GetOrderOfAccuracy(self)


    def SetDirection(self, _arg: 'unsigned int const') -> "void":
        """SetDirection(itkHigherOrderAccurateDerivativeImageFilterIF2IF2 self, unsigned int const _arg)"""
        return _itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF2IF2_SetDirection(self, _arg)


    def GetDirection(self) -> "unsigned int":
        """GetDirection(itkHigherOrderAccurateDerivativeImageFilterIF2IF2 self) -> unsigned int"""
        return _itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF2IF2_GetDirection(self)


    def SetUseImageSpacingOn(self) -> "void":
        """SetUseImageSpacingOn(itkHigherOrderAccurateDerivativeImageFilterIF2IF2 self)"""
        return _itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF2IF2_SetUseImageSpacingOn(self)


    def SetUseImageSpacingOff(self) -> "void":
        """SetUseImageSpacingOff(itkHigherOrderAccurateDerivativeImageFilterIF2IF2 self)"""
        return _itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF2IF2_SetUseImageSpacingOff(self)


    def SetUseImageSpacing(self, _arg: 'bool const') -> "void":
        """SetUseImageSpacing(itkHigherOrderAccurateDerivativeImageFilterIF2IF2 self, bool const _arg)"""
        return _itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF2IF2_SetUseImageSpacing(self, _arg)


    def GetUseImageSpacing(self) -> "bool":
        """GetUseImageSpacing(itkHigherOrderAccurateDerivativeImageFilterIF2IF2 self) -> bool"""
        return _itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF2IF2_GetUseImageSpacing(self)

    __swig_destroy__ = _itkHigherOrderAccurateDerivativeImageFilterPython.delete_itkHigherOrderAccurateDerivativeImageFilterIF2IF2

    def cast(obj: 'itkLightObject') -> "itkHigherOrderAccurateDerivativeImageFilterIF2IF2 *":
        """cast(itkLightObject obj) -> itkHigherOrderAccurateDerivativeImageFilterIF2IF2"""
        return _itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF2IF2_cast(obj)

    cast = staticmethod(cast)

    def New(*args, **kargs):
        """New() -> itkHigherOrderAccurateDerivativeImageFilterIF2IF2

        Create a new object of the class itkHigherOrderAccurateDerivativeImageFilterIF2IF2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkHigherOrderAccurateDerivativeImageFilterIF2IF2.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkHigherOrderAccurateDerivativeImageFilterIF2IF2.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkHigherOrderAccurateDerivativeImageFilterIF2IF2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkHigherOrderAccurateDerivativeImageFilterIF2IF2.Clone = new_instancemethod(_itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF2IF2_Clone, None, itkHigherOrderAccurateDerivativeImageFilterIF2IF2)
itkHigherOrderAccurateDerivativeImageFilterIF2IF2.SetOrder = new_instancemethod(_itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF2IF2_SetOrder, None, itkHigherOrderAccurateDerivativeImageFilterIF2IF2)
itkHigherOrderAccurateDerivativeImageFilterIF2IF2.GetOrder = new_instancemethod(_itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF2IF2_GetOrder, None, itkHigherOrderAccurateDerivativeImageFilterIF2IF2)
itkHigherOrderAccurateDerivativeImageFilterIF2IF2.SetOrderOfAccuracy = new_instancemethod(_itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF2IF2_SetOrderOfAccuracy, None, itkHigherOrderAccurateDerivativeImageFilterIF2IF2)
itkHigherOrderAccurateDerivativeImageFilterIF2IF2.GetOrderOfAccuracy = new_instancemethod(_itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF2IF2_GetOrderOfAccuracy, None, itkHigherOrderAccurateDerivativeImageFilterIF2IF2)
itkHigherOrderAccurateDerivativeImageFilterIF2IF2.SetDirection = new_instancemethod(_itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF2IF2_SetDirection, None, itkHigherOrderAccurateDerivativeImageFilterIF2IF2)
itkHigherOrderAccurateDerivativeImageFilterIF2IF2.GetDirection = new_instancemethod(_itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF2IF2_GetDirection, None, itkHigherOrderAccurateDerivativeImageFilterIF2IF2)
itkHigherOrderAccurateDerivativeImageFilterIF2IF2.SetUseImageSpacingOn = new_instancemethod(_itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF2IF2_SetUseImageSpacingOn, None, itkHigherOrderAccurateDerivativeImageFilterIF2IF2)
itkHigherOrderAccurateDerivativeImageFilterIF2IF2.SetUseImageSpacingOff = new_instancemethod(_itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF2IF2_SetUseImageSpacingOff, None, itkHigherOrderAccurateDerivativeImageFilterIF2IF2)
itkHigherOrderAccurateDerivativeImageFilterIF2IF2.SetUseImageSpacing = new_instancemethod(_itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF2IF2_SetUseImageSpacing, None, itkHigherOrderAccurateDerivativeImageFilterIF2IF2)
itkHigherOrderAccurateDerivativeImageFilterIF2IF2.GetUseImageSpacing = new_instancemethod(_itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF2IF2_GetUseImageSpacing, None, itkHigherOrderAccurateDerivativeImageFilterIF2IF2)
itkHigherOrderAccurateDerivativeImageFilterIF2IF2_swigregister = _itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF2IF2_swigregister
itkHigherOrderAccurateDerivativeImageFilterIF2IF2_swigregister(itkHigherOrderAccurateDerivativeImageFilterIF2IF2)

def itkHigherOrderAccurateDerivativeImageFilterIF2IF2___New_orig__() -> "itkHigherOrderAccurateDerivativeImageFilterIF2IF2_Pointer":
    """itkHigherOrderAccurateDerivativeImageFilterIF2IF2___New_orig__() -> itkHigherOrderAccurateDerivativeImageFilterIF2IF2_Pointer"""
    return _itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF2IF2___New_orig__()

def itkHigherOrderAccurateDerivativeImageFilterIF2IF2_cast(obj: 'itkLightObject') -> "itkHigherOrderAccurateDerivativeImageFilterIF2IF2 *":
    """itkHigherOrderAccurateDerivativeImageFilterIF2IF2_cast(itkLightObject obj) -> itkHigherOrderAccurateDerivativeImageFilterIF2IF2"""
    return _itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF2IF2_cast(obj)

class itkHigherOrderAccurateDerivativeImageFilterIF3IF3(itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    """Proxy of C++ itkHigherOrderAccurateDerivativeImageFilterIF3IF3 class."""

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "itkHigherOrderAccurateDerivativeImageFilterIF3IF3_Pointer":
        """__New_orig__() -> itkHigherOrderAccurateDerivativeImageFilterIF3IF3_Pointer"""
        return _itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF3IF3___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "itkHigherOrderAccurateDerivativeImageFilterIF3IF3_Pointer":
        """Clone(itkHigherOrderAccurateDerivativeImageFilterIF3IF3 self) -> itkHigherOrderAccurateDerivativeImageFilterIF3IF3_Pointer"""
        return _itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF3IF3_Clone(self)

    SignedOutputPixelType = _itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF3IF3_SignedOutputPixelType

    def SetOrder(self, _arg: 'unsigned int const') -> "void":
        """SetOrder(itkHigherOrderAccurateDerivativeImageFilterIF3IF3 self, unsigned int const _arg)"""
        return _itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF3IF3_SetOrder(self, _arg)


    def GetOrder(self) -> "unsigned int":
        """GetOrder(itkHigherOrderAccurateDerivativeImageFilterIF3IF3 self) -> unsigned int"""
        return _itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF3IF3_GetOrder(self)


    def SetOrderOfAccuracy(self, _arg: 'unsigned int const') -> "void":
        """SetOrderOfAccuracy(itkHigherOrderAccurateDerivativeImageFilterIF3IF3 self, unsigned int const _arg)"""
        return _itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF3IF3_SetOrderOfAccuracy(self, _arg)


    def GetOrderOfAccuracy(self) -> "unsigned int":
        """GetOrderOfAccuracy(itkHigherOrderAccurateDerivativeImageFilterIF3IF3 self) -> unsigned int"""
        return _itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF3IF3_GetOrderOfAccuracy(self)


    def SetDirection(self, _arg: 'unsigned int const') -> "void":
        """SetDirection(itkHigherOrderAccurateDerivativeImageFilterIF3IF3 self, unsigned int const _arg)"""
        return _itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF3IF3_SetDirection(self, _arg)


    def GetDirection(self) -> "unsigned int":
        """GetDirection(itkHigherOrderAccurateDerivativeImageFilterIF3IF3 self) -> unsigned int"""
        return _itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF3IF3_GetDirection(self)


    def SetUseImageSpacingOn(self) -> "void":
        """SetUseImageSpacingOn(itkHigherOrderAccurateDerivativeImageFilterIF3IF3 self)"""
        return _itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF3IF3_SetUseImageSpacingOn(self)


    def SetUseImageSpacingOff(self) -> "void":
        """SetUseImageSpacingOff(itkHigherOrderAccurateDerivativeImageFilterIF3IF3 self)"""
        return _itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF3IF3_SetUseImageSpacingOff(self)


    def SetUseImageSpacing(self, _arg: 'bool const') -> "void":
        """SetUseImageSpacing(itkHigherOrderAccurateDerivativeImageFilterIF3IF3 self, bool const _arg)"""
        return _itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF3IF3_SetUseImageSpacing(self, _arg)


    def GetUseImageSpacing(self) -> "bool":
        """GetUseImageSpacing(itkHigherOrderAccurateDerivativeImageFilterIF3IF3 self) -> bool"""
        return _itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF3IF3_GetUseImageSpacing(self)

    __swig_destroy__ = _itkHigherOrderAccurateDerivativeImageFilterPython.delete_itkHigherOrderAccurateDerivativeImageFilterIF3IF3

    def cast(obj: 'itkLightObject') -> "itkHigherOrderAccurateDerivativeImageFilterIF3IF3 *":
        """cast(itkLightObject obj) -> itkHigherOrderAccurateDerivativeImageFilterIF3IF3"""
        return _itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF3IF3_cast(obj)

    cast = staticmethod(cast)

    def New(*args, **kargs):
        """New() -> itkHigherOrderAccurateDerivativeImageFilterIF3IF3

        Create a new object of the class itkHigherOrderAccurateDerivativeImageFilterIF3IF3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkHigherOrderAccurateDerivativeImageFilterIF3IF3.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkHigherOrderAccurateDerivativeImageFilterIF3IF3.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkHigherOrderAccurateDerivativeImageFilterIF3IF3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkHigherOrderAccurateDerivativeImageFilterIF3IF3.Clone = new_instancemethod(_itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF3IF3_Clone, None, itkHigherOrderAccurateDerivativeImageFilterIF3IF3)
itkHigherOrderAccurateDerivativeImageFilterIF3IF3.SetOrder = new_instancemethod(_itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF3IF3_SetOrder, None, itkHigherOrderAccurateDerivativeImageFilterIF3IF3)
itkHigherOrderAccurateDerivativeImageFilterIF3IF3.GetOrder = new_instancemethod(_itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF3IF3_GetOrder, None, itkHigherOrderAccurateDerivativeImageFilterIF3IF3)
itkHigherOrderAccurateDerivativeImageFilterIF3IF3.SetOrderOfAccuracy = new_instancemethod(_itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF3IF3_SetOrderOfAccuracy, None, itkHigherOrderAccurateDerivativeImageFilterIF3IF3)
itkHigherOrderAccurateDerivativeImageFilterIF3IF3.GetOrderOfAccuracy = new_instancemethod(_itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF3IF3_GetOrderOfAccuracy, None, itkHigherOrderAccurateDerivativeImageFilterIF3IF3)
itkHigherOrderAccurateDerivativeImageFilterIF3IF3.SetDirection = new_instancemethod(_itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF3IF3_SetDirection, None, itkHigherOrderAccurateDerivativeImageFilterIF3IF3)
itkHigherOrderAccurateDerivativeImageFilterIF3IF3.GetDirection = new_instancemethod(_itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF3IF3_GetDirection, None, itkHigherOrderAccurateDerivativeImageFilterIF3IF3)
itkHigherOrderAccurateDerivativeImageFilterIF3IF3.SetUseImageSpacingOn = new_instancemethod(_itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF3IF3_SetUseImageSpacingOn, None, itkHigherOrderAccurateDerivativeImageFilterIF3IF3)
itkHigherOrderAccurateDerivativeImageFilterIF3IF3.SetUseImageSpacingOff = new_instancemethod(_itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF3IF3_SetUseImageSpacingOff, None, itkHigherOrderAccurateDerivativeImageFilterIF3IF3)
itkHigherOrderAccurateDerivativeImageFilterIF3IF3.SetUseImageSpacing = new_instancemethod(_itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF3IF3_SetUseImageSpacing, None, itkHigherOrderAccurateDerivativeImageFilterIF3IF3)
itkHigherOrderAccurateDerivativeImageFilterIF3IF3.GetUseImageSpacing = new_instancemethod(_itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF3IF3_GetUseImageSpacing, None, itkHigherOrderAccurateDerivativeImageFilterIF3IF3)
itkHigherOrderAccurateDerivativeImageFilterIF3IF3_swigregister = _itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF3IF3_swigregister
itkHigherOrderAccurateDerivativeImageFilterIF3IF3_swigregister(itkHigherOrderAccurateDerivativeImageFilterIF3IF3)

def itkHigherOrderAccurateDerivativeImageFilterIF3IF3___New_orig__() -> "itkHigherOrderAccurateDerivativeImageFilterIF3IF3_Pointer":
    """itkHigherOrderAccurateDerivativeImageFilterIF3IF3___New_orig__() -> itkHigherOrderAccurateDerivativeImageFilterIF3IF3_Pointer"""
    return _itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF3IF3___New_orig__()

def itkHigherOrderAccurateDerivativeImageFilterIF3IF3_cast(obj: 'itkLightObject') -> "itkHigherOrderAccurateDerivativeImageFilterIF3IF3 *":
    """itkHigherOrderAccurateDerivativeImageFilterIF3IF3_cast(itkLightObject obj) -> itkHigherOrderAccurateDerivativeImageFilterIF3IF3"""
    return _itkHigherOrderAccurateDerivativeImageFilterPython.itkHigherOrderAccurateDerivativeImageFilterIF3IF3_cast(obj)


def higher_order_accurate_derivative_image_filter(*args, **kwargs):
    """Procedural interface for HigherOrderAccurateDerivativeImageFilter"""
    import itk
    instance = itk.HigherOrderAccurateDerivativeImageFilter.New(*args, **kwargs)
    return instance.__internal_call__()

def higher_order_accurate_derivative_image_filter_init_docstring():
    import itk
    import itkTemplate
    if isinstance(itk.HigherOrderAccurateDerivativeImageFilter, itkTemplate.itkTemplate):
        higher_order_accurate_derivative_image_filter.__doc__ = itk.HigherOrderAccurateDerivativeImageFilter.values()[0].__doc__
    else:
        higher_order_accurate_derivative_image_filter.__doc__ = itk.HigherOrderAccurateDerivativeImageFilter.__doc__




