
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-06-01T13:04:05-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "8f105ec684a343ff23ed9b9d156ced243089182e",
 "version": "0.0a5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
