[tool.poetry]
name = "xoinvader"
version = "0.1.1"
description = "(not so) small python curses space game"
authors = ["Pavel Kulyov <kulyov.pavel@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3"
tornado = "^4"
pygame = "*"

[tool.poetry.dev-dependencies]
codecov = "*"
flake8 = "*"
pylint = "*"
pytest = "*"
pytest-coverage = "*"
pytest-pylint = "*"
sphinx = "*"
tox = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
