
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-06-05T10:51:40+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e7bcf9434d576ff63d68ea932b659295e3939edf",
 "version": "0.0.49"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
