
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-06-13T17:45:25+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f015e25ddd3849e3e99e98ecaf3c77cb44f16d48",
 "version": "0.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
