- project:
    templates:
      - build-openstack-docs-pti
      - docs-on-readthedocs
      - openstack-cover-jobs
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - openstack-python37-jobs
      - publish-to-pypi
      - release-notes-jobs-python3
    vars:
        rtd_webhook_id: 'b122e0704a91334a457a33fecc4ea1d432905828'
    check:
      jobs:
        - openstack-tox-pylint
        - tobiko-devstack-functional
        - tobiko-devstack-scenario-centos-7
        - tobiko-devstack-scenario-centos-7-queens
        - tobiko-devstack-scenario-centos-7-rocky
        - tobiko-devstack-scenario-centos-7-stein
        - tobiko-devstack-scenario-fedora-28
        - tobiko-devstack-scenario-ubuntu-bionic

    gate:
      jobs:
        - openstack-tox-pylint
