
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "a8435c98601e182d5bdf2136434ab71d65689b6d",
 "version": "0.20.2.b4150"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
