
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-06-06T19:53:51-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e344171af188a01df74a9f6fe3c620aa2d85de7d",
 "version": "0.5.4-rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
