[tool.poetry]
name = "jrdb"
version = "0.2.0"
description = ""
authors = ["otomarukanta <kanta208@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.21"
lxml = "^4.3"
google-cloud-storage = "^1.13"
fastavro = "^0.21.18"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
