
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "authors": [
  "Padraic Shafer"
 ],
 "date": "2019-06-07T06:44:55-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "84a231bb4b2d3f107ec2b774aeffae23841bb248",
 "version": "0.15.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
