
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": true,
 "error": null,
 "full-revisionid": "ae658f91d7f504df66811cc98037aece08b98f84",
 "version": "0.22.9.b4296"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
