organisation_sizes = [
    (u"Micro", "1 to 10 Employees"),
    (u"Small", "11 to 50 Employees"),
    (u"Medium", "50 to 250 Employees"),
    (u"Large", "250 to 2000 Employees"),
    (u"Marco", "2000+ Employees"),
]


organisation_types = [
    u"Public Company",
    u"Educational Institution",
    u"Self-Employed",
    u"Government Agency",
    u"Non-profit",
    u"Sole Proprietorship",
    u"Privately Held",
    u"Partnership",
    u"Not-enlisted as yet"
]


industries = [
    u"Accounting",
    u"Airlines/Aviation",
    u"Alternative Dispute Resolution",
    u"Alternative Medicine",
    u"Animation",
    u"Apparel and Fashion",
    u"Architecture and Planning",
    u"Arts and Crafts",
    u"Automotive",
    u"Aviation and Aerospace",
    u"Banking",
    u"Biotechnology",
    u"Broadcast Media",
    u"Building Materials",
    u"Business Supplies and Equipment",
    u"Capital Markets",
    u"Chemicals",
    u"Civic and Social Organization",
    u"Civil Engineering",
    u"Commercial Real Estate",
    u"Computer and Network Security",
    u"Computer Games",
    u"Computer Hardware",
    u"Computer Networking",
    u"Computer Software",
    u"Construction",
    u"Consumer Electronics",
    u"Consumer Goods",
    u"Consumer Services",
    u"Cosmetics",
    u"Dairy",
    u"Defense and Space",
    u"Design",
    u"Education Management",
    u"E-Learning",
    u"Electrical/Electronic Manufacturing",
    u"Entertainment",
    u"Environmental Services",
    u"Events Services",
    u"Executive Office",
    u"Facilities Services",
    u"Farming",
    u"Financial Services",
    u"Fine Art",
    u"Fishery",
    u"Food and Beverages",
    u"Food Production",
    u"Fund-Raising",
    u"Furniture",
    u"Gambling and Casinos",
    u"Glass, Ceramics and Concrete",
    u"Government Administration",
    u"Government Relations",
    u"Graphic Design",
    u"Health, Wellness and Fitness",
    u"Higher Education",
    u"Hospital and Health Care",
    u"Hospitality",
    u"Human Resources",
    u"Import and Export",
    u"Individual and Family Services",
    u"Industrial Automation",
    u"Information Services",
    u"Information Technology and Services",
    u"Insurance",
    u"International Affairs",
    u"International Trade and Development",
    u"Internet",
    u"Investment Banking",
    u"Investment Management",
    u"Judiciary",
    u"Law Enforcement",
    u"Law Practice",
    u"Legal Services",
    u"Legislative Office",
    u"Leisure, Travel and Tourism",
    u"Libraries",
    u"Logistics and Supply Chain",
    u"Luxury Goods and Jewelry",
    u"Machinery",
    u"Management Consulting",
    u"Maritime",
    u"Marketing and Advertising",
    u"Market Research",
    u"Mechanical or Industrial Engineering",
    u"Media Production",
    u"Medical Devices",
    u"Medical Practice",
    u"Mental Health Care",
    u"Military",
    u"Mining and Metals",
    u"Mobile Apps Development",
    u"Motion Pictures and Film",
    u"Museums and Institutions",
    u"Music",
    u"Nanotechnology",
    u"Newspapers",
    u"Nonprofit Organization Management",
    u"Oil and Energy",
    u"Online Media",
    u"Outsourcing/Offshoring",
    u"Package/Freight Delivery",
    u"Packaging and Containers",
    u"Paper and Forest Products",
    u"Performing Arts",
    u"Pharmaceuticals",
    u"Philanthropy",
    u"Photography",
    u"Plastics",
    u"Political Organization",
    u"Primary/Secondary Education",
    u"Printing",
    u"Professional Training and Coaching",
    u"Program Development",
    u"Public Policy",
    u"Public Relations and Communications",
    u"Public Safety",
    u"Publishing",
    u"Railroad Manufacture",
    u"Ranching",
    u"Real Estate",
    u"Recreational Facilities and Services",
    u"Religious Institutions",
    u"Renewables and Environment",
    u"Research",
    u"Restaurants",
    u"Retail",
    u"Security and Investigations",
    u"Semiconductors",
    u"Shipbuilding",
    u"Shipping",
    u"Social Networking",
    u"Software Development",
    u"Sporting Goods",
    u"Sports",
    u"Staffing and Recruiting",
    u"Supermarkets",
    u"Telecommunications",
    u"Textiles",
    u"Think Tanks",
    u"Tobacco",
    u"Translation and Localization",
    u"Transportation/Trucking/Railroad",
    u"Utilities",
    u"Venture Capital and Private Equity",
    u"Veterinary",
    u"Warehousing",
    u"Web Development",
    u"Wholesale",
    u"Wine and Spirits",
    u"Wireless",
    u"Writing and Editing"
]