# Generated by Django 2.1.8 on 2019-04-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleboxdjango', '0007_auto_20190425_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='ecommerce_low_stock_threshold',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='stock_count',
            field=models.IntegerField(default=0),
        ),
    ]
