# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-06 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_core_translation_fields'),
        ('surveys', '0029_auto_20180829_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='molosurveypage',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.SiteLanguage'),
        ),
        migrations.AddField(
            model_name='molosurveypage',
            name='translated_pages',
            field=models.ManyToManyField(blank=True, related_name='_molosurveypage_translated_pages_+', to='surveys.MoloSurveyPage'),
        ),
        migrations.AddField(
            model_name='termsandconditionsindexpage',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.SiteLanguage'),
        ),
        migrations.AddField(
            model_name='termsandconditionsindexpage',
            name='translated_pages',
            field=models.ManyToManyField(blank=True, related_name='_termsandconditionsindexpage_translated_pages_+', to='surveys.TermsAndConditionsIndexPage'),
        ),
    ]
