---
features:
  - |
    A new service, NeutronAZConfig, is avaialable which can be used to configure
    Neutron for using avaialabiity zones. By default the service is mapped to
    None, but can be enabled by including `environments/neutron-az-config.yaml`.
    ``NeutronDefaultAvailabilityZones``, ``NeutronDhcpAgentAvailabilityZone``,
    ``NeutronL3AgentAvailabilityZone``, ``NeutronDhcpAgentsPerNetwork``,
    ``NeutronNetworkSchedulerDriver``, ``NeutronRouterSchedulerDriver`` and
    ``NeutronDhcpLoadType`` parameters can be used to configure various AZ
    configurations. By default, ``Neutron*AvailabilityZone`` takes the name of
    the heat stack/deployment plan, and ``NeutronDefaultAvailabilityZones``
    takes an additional value 'nova'. For details, see
    `Official Documentaion <https://docs.openstack.org/neutron/latest/admin/config-az.html>`_.    
