
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "e830a5cd015254a04d326d56b2d23f307b5acf56",
 "version": "0.22.4.b4224"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
