// File: dut.v
// Generated by MyHDL 0.10
// Date: Tue May  8 20:56:15 2018


`timescale 1ns/10ps

module dut (

);



reg [6:0] count;



initial begin: DUT_SEQ
    integer i;
    count <= 50;
    for (i=0; i<300; i=i+1) begin
        # 10;
        $write("%h", count);
        $write("\n");
        if ((($signed({1'b0, count}) - 1) < 0)) begin
            count <= 97;
        end
        else begin
            count <= (count - 1);
        end
    end
end

endmodule
