
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-06-09T09:00:47+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "09f92534a8b82fa1104f432b8487c00ed38de282",
 "version": "3.0.0a22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
