
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "9d76ba316b9aa2180a02a464dad41ed959527c89",
 "version": "0.22.0.b4175"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
