- project:
    templates:
      - openstack-python-jobs
      - openstack-python36-jobs
      - check-requirements
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - bifrost-integration-tinyipa-ubuntu-xenial
        - bifrost-integration-tinyipa-keystone-ubuntu-xenial
        - bifrost-integration-tinyipa-opensuse-423
        - bifrost-integration-tinyipa-opensuse-150
        # Non-voting jobs
        - bifrost-integration-dhcp-ubuntu-xenial:
            voting: false
        - bifrost-integration-dhcp-opensuse-423:
            voting: false
        - bifrost-integration-dhcp-opensuse-150:
            voting: false
        - bifrost-integration-dhcp-centos-7:
            voting: false
        - bifrost-integration-dibipa-debian-centos-7:
            voting: false
        - bifrost-integration-dibipa-debian-ubuntu-xenial:
            voting: false
        - bifrost-integration-dibipa-debian-opensuse-423:
            voting: false
        - bifrost-integration-dibipa-debian-opensuse-150:
            voting: false
        - bifrost-integration-tinyipa-centos-7:
            voting: false
        - openstack-tox-lower-constraints
    gate:
      jobs:
        - bifrost-integration-tinyipa-ubuntu-xenial
        - bifrost-integration-tinyipa-keystone-ubuntu-xenial
        - bifrost-integration-tinyipa-opensuse-423
        - bifrost-integration-tinyipa-opensuse-150
        - openstack-tox-lower-constraints
