
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-21T10:41:25+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "6fb083477bc0b1f3eeccc62e10e4b477ae532346",
 "version": "0.6.20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
