# Generated by Django 2.1.8 on 2019-04-23 04:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saleboxdjango', '0005_auto_20190419_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=50)),
                ('transaction_guid', models.CharField(blank=True, max_length=20, null=True)),
                ('salebox_member_id', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('processed_flag', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.DeleteModel(
            name='TransactionEvent',
        ),
    ]
