[tool.poetry]
name = "srec_nlp"
version = "0.1.0"
description = ""
authors = ["Stelios Tymvios <stelios.tymvios@icloud.com>"]

[tool.poetry.dependencies]
python = "^3.7"
ibm-watson = "^3.0"
google-cloud-language = "^1.2"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
autopep8 = {version = "^1.4",optional = true}
black = {version = "^18.3-alpha.0",allows-prereleases = true}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
