__title__ = 'slowbreak'
__description__ = 'Library to connect to FIX servers, and make our own'
__url__ = 'https://bitbucket.org/aurelito/slowbreak/'
__version__ = '0.0.16'
__author__ = 'Aureliano Calvo'
__author_email__ = 'aurelianocalvo@gmail.com'
__license__ = 'MIT'
__copyright__ = 'Copyright 2018-2019 Aureliano Calvo'