# coding: utf-8

"""
    Felix' Website mit Blog

    The api of my blog.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: felix@felix-scholz.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import website_python_client
from models.acl import Acl  # noqa: E501
from website_python_client.rest import ApiException


class TestAcl(unittest.TestCase):
    """Acl unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAcl(self):
        """Test Acl"""
        # FIXME: construct object with mandatory attributes with example values
        # model = website_python_client.models.acl.Acl()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
