# coding: utf-8

"""
    Felix' Website mit Blog

    The api of my blog.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: felix@felix-scholz.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import website_python_client
from api.tag_api import TagApi  # noqa: E501
from website_python_client.rest import ApiException


class TestTagApi(unittest.TestCase):
    """TagApi unit test stubs"""

    def setUp(self):
        self.api = api.tag_api.TagApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_tag(self):
        """Test case for create_tag

        create a new tag  # noqa: E501
        """
        pass

    def test_delete_tag(self):
        """Test case for delete_tag

        delete a tag  # noqa: E501
        """
        pass

    def test_get_tag(self):
        """Test case for get_tag

        get a tag  # noqa: E501
        """
        pass

    def test_list_tags(self):
        """Test case for list_tags

        Returned all tags  # noqa: E501
        """
        pass

    def test_update_tag(self):
        """Test case for update_tag

        update a tag  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
