[tool.poetry]
name = "GenconMiner"
version = "0.1.7"
description = "Wraps Pip packages (beautifulsoup and requests) to a more concise content extractor"
readme = "README.md"
authors = ["Almer Mendoza <amendoza@stratpoint.com>"]
license = "MIT"
repository = "https://github.com/mamerisawesome/GenconMiner"
packages = [
    { include = "gencon_miner" }
]

[tool.poetry.scripts]
jupyter = 'scripts:jupyter'

[tool.poetry.dependencies]
python = "^3.6 || ^2.7"
beautifulsoup4 = "^4.7"
requests = "^2"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
