[tool.poetry]
name = "hilde"
version = "0.2.1.dev2"
description = "Haber Institute Lattice Dynamics Environment"
authors = ["Florian Knoop <knoop@fhi-berlin.mpg.de>"]
license = "ISC"
readme = "README.md"
repository = "https://gitlab.com/flokno/hilde"

keywords = ['physics']

build = "build.py"

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.16"
scipy = "^1.3"
matplotlib = "^3.1"
son = "^0.1.4"
spglib = "^1.12"
phonopy = "^2.1"
ase = "^3.17"

[tool.poetry.dev-dependencies]
black = "^18.9b0"

[tool.poetry.scripts]
make_supercell = 'hilde.scripts.make_supercell:main'

[build-system]
requires = ["poetry>=0.12", "numpy"]
build-backend = "poetry.masonry.api"
