
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-29T06:45:05-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "639d91743ade807fcc7c4428a400e81f01628398",
 "version": "v0.5.32"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
