# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-06-05 10:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('cms', '0020_old_tree_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraSlide',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_cameraslider_cameraslide', serialize=False, to='cms.CMSPlugin')),
                ('caption', djangocms_text_ckeditor.fields.HTMLField(blank=True, help_text='Optional caption that is displayed with the image', null=True, verbose_name='caption')),
                ('image', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name': 'Camera Slide',
                'verbose_name_plural': 'Camera Slides',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='CameraSlider',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_cameraslider_cameraslider', serialize=False, to='cms.CMSPlugin')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slider_id', models.CharField(default='camera-slider', help_text='The ID attribute used in the HTML', max_length=100, verbose_name='slider ID')),
                ('slider_config', models.TextField(blank=True, help_text='The JSON object passed to Camera slider. For more info <a target="_blank" href="https://www.jqueryscript.net/slideshow/Camera-Slideshow-Plugin.html">click here</a>', null=True, verbose_name='slider config')),
            ],
            options={
                'verbose_name': 'Camera Slider',
                'verbose_name_plural': 'Camera Sliders',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
