
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": true,
 "error": null,
 "full-revisionid": "7b215166c41b6d350f8b7662a948a93a2f3e4f70",
 "version": "0.22.10.b4329"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
