
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-06-13T16:17:26-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "59ef76317bd8a8c4b0a3b50b5fe21a605eb3c8b0",
 "version": "4.2.11b1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
