#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

install_requires = \
['requests']

setup(name='wideq',
      version='1.0.1',
      description='Reverse-engineered client for the LG SmartThinQ API.',
      author='Adrian Sampson',
      author_email='adrian@radbox.org',
      url='https://github.com/sampsyo/wideq',
      py_modules=['wideq'],
      install_requires=install_requires,
      python_requires='>=3.4',
     )
