# This file is automatically generated from sisl setup.py
released = True

# Git information (specific commit, etc.)
git_revision = '88f92df75cebd1adb6d9b97b608f784c2dd277eb'
git_revision_short = git_revision[:7]
git_count = 0

# Version information
major   = 0
minor   = 9
micro   = 6
version = '.'.join(map(str,[major, minor, micro]))
release = version

if git_count > 2 and not released:
    # Add git-revision to the version string
    version += '+' + str(git_count)

# BibTeX information if people wish to cite
bibtex = '''@misc{{zerothi_sisl,
    author = {{Papior, Nick}},
    title  = {{sisl: v{0}}},
    year   = {{2019}},
    doi    = {{10.5281/zenodo.597181}},
    url    = {{https://doi.org/10.5281/zenodo.597181}},
}}'''.format(version)

def cite():
    return bibtex
