run_id: "20180920_112044" #use with quotes when the name composed of numbers

job_name: test_name

fastq_dir: /home/labs/bioservices/pmrefael/180417_NB501465_0284_AHNYLHBGX5/HNYLHBGX5

output_dir: /home/labs/bioservices/pmrefael/snakemake

adaptor: CTGTCTCTTATACACATCTCCGAGCCCACGAGAC,CTGTCTCTTATACACATCTGACGCTGCCGACGAGTGTAGATCTCGGTGGTCGCCGTATCATT

genome: /shareDB/BioServices/bowtie2_db/mm10/mm10

#The file name must to start with creature alias, for example mm10.bed
tss_file: /home/labs/bioservices/bareket/Yael/ATACscript/ATACpipeline_V2/lib/TSS_+2500_-2500_uniqueProm.bed

#Example of pheno_data file is under the current folder: pheno_data-atacseq.tsv
treat_vs_control: pheno_data-20180920_112044.tsv

##### Don't change it.
scripts: /apps/RH7U2/scripts/bbcu-python-packages/python27-ve-ngs-snakemake/bin

templates: /apps/RH7U2/scripts/bbcu-python-packages/python27-ve-ngs-snakemake/lib/python2.7/site-packages/ngs-snakemake

python: /apps/RH7U2/scripts/bbcu-python-packages/python27-ve-ngs-snakemake/bin/python

Rscript: /apps/RH7U2/gnu/R/3.4.2/bin/Rscript

R_lib_paths: /apps/RH7U2/scripts/bbcu-R-packages

conda_root: /home/labs/bioservices/srevices/miniconda2

java: java

#For internal using, no need full path because we do module load
cutadapt_exe: cutadapt

fastqc_exe: fastqc

multiqc_exe: multiqc

bowtie2_exe: bowtie2

samtools_exe: samtools

picard_exe: /apps/RH7U2/general/picard/2.8.3/picard.jar

igvtools_exe: igvtools # module laod IGVTools

ngs_plot_exe: ngs.plot.r

gs_exe: gs

macs2_exe: macs2

bedtools_exe: bedtools

max_threads_num: 100

#####