---
run_id: "20190407_095641" # Use with quotes when the name composed of numbers
job_name: "20190407_095641_Hadas_wo_JF" #Use with quotes when the name composed of numbers
fastq_dir: /home/labs/shacharlab/Collaboration/Hadas_G_4_patients
output_dir: /home/labs/shacharlab/Collaboration/20190407_095641_Hadas_wo_JF_transcriptome_MARS-seq
factors_file: /home/labs/shacharlab/Collaboration/20190407_095641_Hadas_wo_JF_transcriptome_MARS-seq/pheno_data-20190407_095641.tsv
# The file name must to start with creature alias, for example mm10.gtf
gtf: /home/labs/bioservices/services/ngs/support/gtf/hg38-gencode.genes.3utr.gtf
my_star_index: /shareDB/iGenomes/Homo_sapiens/UCSC/hg38/Sequence/hg38_star_index
##### Don't change these parameters.
scripts: /home/labs/bioservices/services/miniconda2/envs/utap/bin
templates: /home/labs/bioservices/services/miniconda2/envs/utap/lib/python2.7/site-packages/ngs-snakemake
python: /home/labs/bioservices/services/miniconda2/envs/utap/bin/python
Rscript: /home/labs/bioservices/services/miniconda2/envs/utap/bin/Rscript
gs_exe: /home/labs/bioservices/services/miniconda2/envs/utap/bin/gs
R_lib_paths: /home/labs/bioservices/services/miniconda2/envs/utap/lib/R/library
conda_root: /home/labs/bioservices/services/miniconda2
cutadapt_exe: /home/labs/bioservices/services/miniconda2/envs/utap/bin/cutadapt
fastqc_exe: /home/labs/bioservices/services/miniconda2/envs/utap/bin/fastqc
star_exe: /home/labs/bioservices/services/miniconda2/envs/utap/bin/STAR
samtools_exe: /home/labs/bioservices/services/miniconda2/envs/utap/bin/samtools
ngs_plot_exe: module load R/3.4.2;module load ngsplot;ngs.plot.r
htseq_count_exe: /home/labs/bioservices/services/miniconda2/envs/utap/bin/htseq-count
max_threads_num: 100




