run_id: "20180920_112044" #use with quotes when the name composed of numbers

job_name: test_name

fastq_dir: /home/labs/bioservices/pmrefael/180417_NB501465_0284_AHNYLHBGX5/HNYLHBGX5

output_dir: /home/labs/bioservices/pmrefael/snakemake

cellranger_transcriptom: /shareDB/CellRanger/refdata-cellranger-mm10-1.2.0

##### Don't change it.
scripts: /apps/RH7U2/scripts/bbcu-python-packages/python27-ve-ngs-snakemake/bin

templates: /apps/RH7U2/scripts/bbcu-python-packages/python27-ve-ngs-snakemake/lib/python2.7/site-packages/ngs-snakemake

python: /apps/RH7U2/scripts/bbcu-python-packages/python27-ve-ngs-snakemake/bin/python

Rscript: /apps/RH7U2/gnu/R/3.4.2/bin/Rscript

R_lib_paths: /apps/RH7U2/scripts/bbcu-R-packages

#For internal using, no need full path because we do module load
cellranger_exe: cellranger

max_threads_num: 100
#####