---
run_id: "20190412_030519" # Use with quotes when the name composed of numbers
job_name: "20190412_030519_AGO_LIS1_RNAseq" # Use with quotes when the name composed of numbers
fastq_dir: /home/labs/reinerlab/Collaboration/AGO_LIS1_RNAseq
output_dir: /home/labs/reinerlab/Collaboration/20190412_030519_AGO_LIS1_RNAseq_transcriptome_RNA-seq
# The file name must to start with creature alias, for example mm10.gtf
gtf: /home/labs/bioservices/services/ngs/support/gtf/mm10-gencode.genes.gtf
#adaptor to remove from R1 and R2 files respectively
adaptor: AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC,AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT
#'yes', 'no' or enter float number for automate testing (for example: '0.3'): if the proportion of the counts of the one of the strands will be above this value it is stranded protocol, rather it is not stranded protocol)
stranded_protocol: "yes"
factors_file: /home/labs/reinerlab/Collaboration/20190412_030519_AGO_LIS1_RNAseq_transcriptome_RNA-seq/pheno_data-20190412_030519.tsv
##### Don't change these parameters.
scripts: /home/labs/bioservices/services/miniconda2/envs/utap/bin
templates: /home/labs/bioservices/services/miniconda2/envs/utap/lib/python2.7/site-packages/ngs-snakemake
my_star_index: /shareDB/iGenomes/Mus_musculus/UCSC/mm10/Sequence/STAR_index
python: /home/labs/bioservices/services/miniconda2/envs/utap/bin/python
conda_root: /home/labs/bioservices/services/miniconda2
gs_exe: /home/labs/bioservices/services/miniconda2/envs/utap/bin/gs
Rscript: /home/labs/bioservices/services/miniconda2/envs/utap/bin/Rscript
R_lib_paths: /home/labs/bioservices/services/miniconda2/envs/utap/lib/R/library
cutadapt_exe: /home/labs/bioservices/services/miniconda2/envs/utap/bin/cutadapt
fastqc_exe: /home/labs/bioservices/services/miniconda2/envs/utap/bin/fastqc
star_exe: /home/labs/bioservices/services/miniconda2/envs/utap/bin/STAR
samtools_exe: /home/labs/bioservices/services/miniconda2/envs/utap/bin/samtools
ngs_plot_exe: module load R/3.4.2;module load ngsplot;ngs.plot.r
htseq_count_exe: /home/labs/bioservices/services/miniconda2/envs/utap/bin/htseq-count
max_threads_num: 100

