job_name: chipseq

fastq_dir: /home/labs/bioservices/jordanal/chip_seq_jordana/paired/test-refael/h3k_input
#fastq_dir: /home/labs/aramalab/Collaboration/chip-pipeline/input_dir_short

output_dir:  /home/labs/bioservices/jordanal/chip_seq_jordana/paired/test-refael/output_dir

chr_info: /home/labs/bioservices/jordanal/chip_seq_jordana/paired/mm10.len.txt

genomeIndx: /shareDB/iGenomes/Mus_musculus/UCSC/mm10/Sequence/Bowtie2Index/genome 

genome: /shareDB/iGenomes/Mus_musculus/UCSC/mm10/Sequence/Bowtie2Index/genome.fa 

adaptor: AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC,AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT # TruSeq primers adaptors - do we need to add the possibility to chose to remove adaptors 

##### Don't change it.
scripts: /apps/RH7U2/scripts/bbcu-python-packages/python27-ve-ngs-snakemake/bin

templates: /apps/RH7U2/scripts/bbcu-python-packages/python27-ve-ngs-snakemake/lib/python2.7/site-packages/ngs-snakemake

python: /apps/RH7U2/scripts/bbcu-python-packages/python27-ve-ngs-snakemake/bin/python

Rscript: /apps/RH7U2/gnu/R/3.4.2/bin/Rscript

R_lib_paths: /apps/RH7U2/scripts/bbcu-R-packages

fastqc_exe: fastqc

multiQC_exe: multiqc

cutadapt_exe: cutadapt

Homer_exe: homer

bowtie2_exe: bowtie2

samtools_exe: samtools

bedtools_exe: bedtools

flgstats_exe: samtools flagstat

macs_exe: macs2

ngs_plot_exe: ngs.plot.r

run_id: 20181015_155639

#con_vs_treat: pheno_data-20181015_155639.tsv
con_vs_treat: /home/labs/bioservices/jordanal/chip_seq_jordana/paired/test-refael/phenodata.tsv


#####
