
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-28T12:45:15-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "3d978691b7bba950075f8e7baf50a816ea8f3f17",
 "version": "0.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
