[package]
name = "retworkx"
description = "A python graph library implemented in Rust"
version = "0.0.9"
authors = ["Matthew Treinish <mtreinish@kortar.org>"]
license = "Apache-2.0"
readme = "README.rst"
repository = "https://github.com/mtreinish/retworkx"
keywords = ["python", "graph"]

[badges]
travis-ci = {repository = "mtreinish/retworkx"}

[lib]
name = "retworkx"
crate-type = ["cdylib"]

[dependencies]
petgraph = "0.4"
daggy = "0.6"

[dependencies.pyo3]
version = "0.7.0-alpha.1"
features = ["extension-module"]
