
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-06-18T10:55:10-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "a4ce00de4a3e173c2494002304d5fd2b0e9b78ca",
 "version": "0.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
