[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "pyulgresample"
author = "Dennis Mannhart"
author-email = "dennis@yuneecresearch.com"
home-page = "https://github.com/YUNEEC/pyulgresample"
requires=[
        "numpy (>= 1.15.3)",
        "pandas (>= 0.23.4)",
        "pyulog (>= 0.6.0)",
        "utm (>= 0.4.2)",
        "transforms3d",
]
requires-python='>=3.6'
description-file='README.md'
classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'Topic :: Software Development :: Libraries :: Python Modules',
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: BSD License',
        'Operating System :: OS Independent']

[tool.flit.metadata.requires-extra]
requires = [
        "flake8",
        "pre-commit",
]
test = [
    "pytest"
]

[tool.black]
line-length = 79
include = '\.pyi?$'
exclude ='''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | build
  | dist
  | \.eggs
)/
'''