
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-06-14T14:12:01-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "ddb3849e0590938a2eac26ae81fc97bc44fea6e8",
 "version": "0.0.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
