[tool.poetry]
name = "py-buzz"
version = "1.0.3"
description = "\"That's not flying, it's falling with style: Exceptions with extras\""
authors = ["Tucker Beck <tucker.beck@gmail.com>"]
license = "MIT"
copyright = "2016, Tucker Beck"
readme = "README.rst"
packages = [
    { include = 'buzz' }
]

[tool.poetry.dependencies]
python = "^3.5"
deprecated = "^1.2"
inflection = "^0.3.1"

[tool.poetry.dev-dependencies]
flake8 = "^3.7"
pytest = "^4.4"
sphinx = "^2.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
