
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-31T16:11:54-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "d0cc75bdc4ecc28c48708f1cafd012a9dbfb94b9",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
