[tool.poetry]
name = "pillarsdk"
version = "1.10"
description = "The Pillar REST SDK provides Python APIs to communicate to the Pillar webservices."
authors = [
    "Francesco Siddi <francesco@blender.org>",
    "Sybren Stüvel <sybren@blender.studio>",
]
classifiers = [
    'Intended Audience :: Developers',
    'Operating System :: OS Independent',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.5',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Topic :: Software Development :: Libraries :: Python Modules'
]

[tool.poetry.dependencies]
python = "^3.5"
pyOpenSSL = "~19"
requests = "~2"

[tool.poetry.dev-dependencies]
tox = "~3.9"
wheel = "~0.33"
pytest = "~4.4"
pytest-cov = "~2.7"
responses = "~0.10"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
