language: c
sudo: false

compiler:
  - gcc
  - clang

addons:
    apt:
        packages:
            - libjudy-dev libvorbis-dev libportaudio-dev libtalloc-dev

script:
        - make config.h
        - make -j2
        - make -j2 -k check
