# Generated by Django 2.1.8 on 2019-04-19 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saleboxdjango', '0004_transactionevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionevent',
            options={'ordering': ['-created']},
        ),
    ]
