# Generated by Django 2.1.8 on 2019-05-31 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleboxdjango', '0009_auto_20190524_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='stock_checked_out',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='stock_count_total',
            field=models.IntegerField(default=0),
        ),
    ]
