# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0023_add_page_view_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='molosurveypage',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='molosurveypage',
            old_name='intro',
            new_name='introduction',
        ),
        migrations.AlterField(
            model_name='molosurveyformfield',
            name='field_type',
            field=models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), (b'positive_number', 'Positive Number')], max_length=16, verbose_name='field type'),
        ),
        migrations.AlterField(
            model_name='personalisablesurveyformfield',
            name='field_type',
            field=models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), (b'positive_number', 'Positive Number')], max_length=16, verbose_name='field type'),
        ),
    ]
