# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0024_add_molo_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='molosurveypage',
            name='homepage_introduction',
            field=models.TextField(blank=True),
        ),
    ]
