
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2019-06-12T09:53:05+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a0f6772ec9283b74e970973498396868d6e03ff1",
 "version": "2019.6.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
