- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - check-requirements
      - openstack-lower-constraints-jobs
      - release-notes-jobs-python3
      - publish-openstack-docs-pti
    check:
      jobs:
        - sushy-tools-tempest-ironic-partition-redfish-src
    gate:
      jobs:
        - sushy-tools-tempest-ironic-partition-redfish-src
