[tool.poetry]
name = "checkstat"
version = "0.1.1"
description = ""
authors = ["Franccesco Orozco <franccesco@codingdose.info>"]

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.0"
colorama = "^0.4.1"
requests = "^2.22"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
checkstat = "checkstat.cli:main"
