
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-31T17:13:09+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1d0e77713c7cfc32c71f62b5331e5a6888838021",
 "version": "0.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
