[tool.poetry]
name = "mb_drf_article"
version = "0.1.0"
description = "An article model for Django-Rest-Framework."
authors = ["mikael briolet <mikaelbriolet.services@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/8area8/drf-articles"
repository = "https://github.com/8area8/drf-articles"
keywords = ["django", "django rest framework", "article"]
classifiers = [
    'Environment :: Web Environment',
    'Framework :: Django',
    'Framework :: Django :: 2.2',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: BSD License',
    'Operating System :: OS Independent',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3.5',
    'Programming Language :: Python :: 3.6',
    'Topic :: Internet :: WWW/HTTP',
    'Topic :: Internet :: WWW/HTTP :: Dynamic Content',
]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
