# coding: utf-8

"""


    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.store_app_version_templete_plugin_config_group import StoreAppVersionTempletePluginConfigGroup  # noqa: E501
from swagger_client.rest import ApiException


class TestStoreAppVersionTempletePluginConfigGroup(unittest.TestCase):
    """StoreAppVersionTempletePluginConfigGroup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStoreAppVersionTempletePluginConfigGroup(self):
        """Test StoreAppVersionTempletePluginConfigGroup"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.store_app_version_templete_plugin_config_group.StoreAppVersionTempletePluginConfigGroup()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
