
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-29T09:20:57-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "64c112a9a8d5a9fa013378a32331ebfd84ca6b53",
 "version": "0.2.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
