[tool.poetry]
name = "spkcspider"
description = "A secure, decentral platform for maintaining your online identity"
version = "0.8a4"
license = "MIT"
authors = ["Alexander Kaftan"]
homepage = "https://spkcspider.net"
readme = "README.md"
repository = "https://https://github.com/spkcspider/spkcspider"
classifiers = [
  "Development Status :: 4 - Beta",
  "Framework :: Django",
  "Intended Audience :: System Administrators",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Operating System :: POSIX",
  "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
  "Topic :: Internet :: WWW/HTTP :: Dynamic Content :: Content Management System",
  "Topic :: Internet :: WWW/HTTP :: WSGI :: Application"
]

keywords = [
  "online identity", "decentral networks"
]

[tool.poetry.dependencies]
python = ">=3.5"
django = '>=2.2'
django-simple-jsonfield = '>=0.3'
requests = '*'
certifi = '*'
bleach = '*'
rdflib = '*'
html5lib = '*'
cryptography = "*"
django-ranged-response = "*"
django-widget-tweaks = "*"
django-next-prev = "*"
django-fast-ratelimit = "*"
lru-dict = "*"

[tool.poetry.dev-dependencies]
django-extensions = '*'
Werkzeug = '*'
pyOpenSSL = '*'
django-simple-captcha = "*"

[tool.poetry.extras]
captcha = ["django-simple-captcha"]
fcgi = ["flipflop"]
mysql = ["mysqlclient"]
pgsql = ["psycopg-binary"]
celery = ["celery", "sqlalchemy"]
test = ["django-webtest", "django-simple-captcha", "WSGIProxy2", "celery"]

[tool.tox]
legacy_tox_ini = """
[tox]
minversion = 3.4.0
skipsdist=true
envlist = py{35,36,37}-django{22,master}

[testenv]
commands = python -Wd ./manage.py test


setenv =
    PYTHONDONTWRITEBYTECODE=1

deps =
  django-simple-jsonfield>=0.3
  requests
  certifi
  bleach
  rdflib
  html5lib
  cryptography
  django-ranged-response
  django-widget-tweaks
  django-next-prev
  django-fast-ratelimit
  lru-dict
  django-webtest
  django-simple-captcha
  WSGIProxy2
  celery
  django22: Django>=2.2a1,<=2.2.99
  djangomaster: https://github.com/django/django/archive/master.zip

"""

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
