
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-31T15:01:27+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "7ef31ccfe80d869303fc2cc872141b17f5ad904c",
 "version": "5.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
