{
 "title": "Conductividad eléctrica fibra",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Conductividad electrica Sucy blue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "dS/m" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__time(date), value AS \"Conductividad electrica\" from sensors_data_fibersensor WHERE fiber_sensor_id = 13 AND variable_id = 186;"
    }
   ]
  },
  {
   "title": "Conductividad electrica Plastico",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "dS/m" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__time(date), value AS \"Conductividad electrica\" from sensors_data_fibersensor WHERE fiber_sensor_id = 12 AND variable_id = 186;"
    }
   ]
  },
  {
   "title": "Conductividad electrica Ensayo",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "dS/m" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__time(date), value AS \"Conductividad electrica\" from sensors_data_fibersensor WHERE fiber_sensor_id = 2 AND variable_id = 186;"
    }
   ]
  },
  {
   "title": "Conductividad electrica Cerezos",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "dS/m" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__time(date), value AS \"Conductividad electrica\" from sensors_data_fibersensor WHERE fiber_sensor_id = 14 AND variable_id = 186;"
    }
   ]
  },
  {
   "title": "Conductividad electrica Malla",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "dS/m" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__time(date), value AS \"Conductividad electrica\" from sensors_data_fibersensor WHERE fiber_sensor_id = 1 AND variable_id = 186;"
    }
   ]
  }
 ]
}