
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-06-06T19:07:04+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "8486b92d17e713ee21b0a31d511ed71dd75caa63",
 "version": "0.10.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
