
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-06-16T15:35:29-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e3ae98f92eaa346316c54a8520a54a19ad4eda13",
 "version": "0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
