
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-06-12T00:46:53-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "7e709a4ad06cb8123fe92afa89c2195bf96fac61",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
