import setuptools

with open("README.md", "r") as fh:
    long_description = fh.read()

setuptools.setup(
    name="pitchplots",
    version="1.3.4",
    author="Fabian Moss",
    author_email="fabian.moss@epfl.ch",
    description="A package containing representation tools for musical purposes",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/DCMLab/pitchplots",
    packages=setuptools.find_packages(),
    package_data={
            'pitchplots': ['data/data_example.mxl', 'data/silence.wav', 'data/midi21.wav',
                           'data/midi22.wav', 'data/midi23.wav', 'data/midi24.wav',
                           'data/midi25.wav', 'data/midi26.wav', 'data/midi27.wav',
                           'data/midi28.wav', 'data/midi29.wav', 'data/midi30.wav',
                           'data/midi31.wav', 'data/midi32.wav', 'data/midi33.wav',
                           'data/midi34.wav', 'data/midi35.wav', 'data/midi36.wav',
                           'data/midi37.wav', 'data/midi38.wav', 'data/midi39.wav',
                           'data/midi40.wav', 'data/midi41.wav', 'data/midi42.wav',
                           'data/midi43.wav', 'data/midi44.wav', 'data/midi45.wav',
                           'data/midi46.wav', 'data/midi47.wav', 'data/midi48.wav',
                           'data/midi49.wav', 'data/midi50.wav', 'data/midi51.wav',
                           'data/midi52.wav', 'data/midi53.wav', 'data/midi54.wav',
                           'data/midi55.wav', 'data/midi56.wav', 'data/midi57.wav',
                           'data/midi58.wav', 'data/midi59.wav', 'data/midi60.wav',
                           'data/midi61.wav', 'data/midi62.wav', 'data/midi63.wav',
                           'data/midi64.wav', 'data/midi65.wav', 'data/midi66.wav',
                           'data/midi67.wav', 'data/midi68.wav', 'data/midi69.wav',
                           'data/midi70.wav', 'data/midi71.wav', 'data/midi72.wav',
                           'data/midi73.wav', 'data/midi74.wav', 'data/midi75.wav',
                           'data/midi76.wav', 'data/midi77.wav', 'data/midi78.wav',
                           'data/midi79.wav', 'data/midi80.wav', 'data/midi81.wav',
                           'data/midi82.wav', 'data/midi83.wav', 'data/midi84.wav',
                           'data/midi85.wav', 'data/midi86.wav', 'data/midi87.wav',
                           'data/midi88.wav', 'data/midi89.wav', 'data/midi90.wav',
                           'data/midi91.wav', 'data/midi92.wav', 'data/midi93.wav',
                           'data/midi94.wav', 'data/midi95.wav', 'data/midi96.wav',
                           'data/midi97.wav', 'data/midi98.wav', 'data/midi99.wav',
                           'data/midi100.wav', 'data/midi101.wav', 'data/midi102.wav',
                           'data/midi103.wav', 'data/midi104.wav', 'data/midi105.wav',
                           'data/midi106.wav', 'data/midi107.wav', 'data/midi108.wav'],
    },
    install_requires=['matplotlib>=3.0.1',
                      'pandas>=0.23.4',
                      'numpy>=1.15.3',
                      'moviepy>=1.0.0'],
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
)