
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-29T17:57:44-0500",
 "dirty": true,
 "error": null,
 "full-revisionid": "30e84098af3e1cf653e35fc62cb757a812b16b47",
 "version": "0.3.30"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
