
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "c84cafda339fad470337b8679feff11f37f3bb34",
 "version": "0.22.1.b4182"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
