
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-06-01T12:29:01-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "1ee7128b323719799804fb2ce62bd4c9f1aa97b9",
 "version": "0.0a10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
