# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-29 09:39
from __future__ import unicode_literals

from django.db import migrations
import molo.surveys.rules


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0028_update_help_text_on_field_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveysubmissiondatarule',
            name='field_name',
            field=molo.surveys.rules.FieldNameField(help_text="Field's label. For possible choices please input any text and save, so it will be displayed in the error messages below the field.", max_length=255, verbose_name='field name'),
        ),
    ]
