
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-29T08:27:58-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "301735b3003860c3cedb837c0a6bc7f8a5cc6f52",
 "version": "3.10.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
