---

undercloud_service_list:
  - openstack-nova-compute
  - openstack-heat-engine
  - openstack-ironic-conductor
  - openstack-swift-container
  - openstack-swift-object
  - openstack-mistral-engine
