#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['darken']

package_data = \
{'': ['*']}

entry_points = \
{'console_scripts': ['darken = darken:main']}

setup(name='darken',
      version='0.0.3',
      description='Apply black only on mdified files',
      author='Matthias Bussonnier',
      author_email='bussonniermatthias@gmail.com',
      url='https://github.com/Carreau/darken',
      packages=packages,
      package_data=package_data,
      entry_points=entry_points,
     )
