- name: Install pip using get-pip.py
  become: yes
  shell: |
      curl https://bootstrap.pypa.io/get-pip.py | python

- name: Install required packages
  become: yes
  vars:
    required_packages: ['python-virtualenv', 'git', 'gcc', 'python-devel', 'wget']
  yum:
      name: "{{ required_packages }}"
      state: present

- name: Clone Tobiko project
  git:
      repo: 'https://review.opendev.org/x/tobiko'
      dest: "{{ test.dir }}"

- name: Create Virtualenv
  vars:
      packages: ['pip', 'setuptools', 'tox']
  pip:
      virtualenv: "{{ test.venv }}"
      name: "{{ packages }}"
      state: latest

- name: Install Tobiko
  pip:
      chdir: "{{ test.dir }}"
      name: "."
      virtualenv: "{{ test.venv }}"
      editable: true
      extra_args: "-c https://opendev.org/openstack/requirements/raw/branch/master/upper-constraints.txt -r {{ test.dir }}/requirements.txt"
