
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-06-04T18:41:53+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "4767ad3cae07bd3a49e944013e0b74b33fd406bc",
 "version": "0.9.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
