
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": true,
 "error": null,
 "full-revisionid": "772465b81073daf666f02b34dc8e074c2627f3f0",
 "version": "0.22.8.b4290"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
