# Autogenerated by Astropy-affiliated package astropy_helpers's setup.py on 2019-05-30 22:58:23 UTC
from __future__ import unicode_literals
import datetime

version = "2.0.8"
githash = "231c409a632dcbf2beae1c2dea5b843d81ede511"


major = 2
minor = 0
bugfix = 8

release = True
timestamp = datetime.datetime(2019, 5, 30, 22, 58, 23)
debug = False

astropy_helpers_version = ""

try:
    from ._compiler import compiler
except ImportError:
    compiler = "unknown"

try:
    from .cython_version import cython_version
except ImportError:
    cython_version = "unknown"
