image: docker:stable

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:
  - build
  - publish

build_job:
  stage: build
  script:
    - docker pull $CI_REGISTRY_IMAGE:3.7 || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:3.7 -t $CI_REGISTRY_IMAGE:3.7 --build-arg PYTHON_VERSION=3.7 .
    - docker run $CI_REGISTRY_IMAGE:3.7 make test
    - docker push $CI_REGISTRY_IMAGE:3.7

publish_job:
  stage: publish
  only:
    - tags
  script:
    - docker pull $CI_REGISTRY_IMAGE:3.7 || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:3.7 -t $CI_REGISTRY_IMAGE:3.7 --build-arg PYTHON_VERSION=3.7 .
    - docker run -e PYPI_USER -e PYPI_PASS $CI_REGISTRY_IMAGE:3.7 make publish
