[tool.poetry]
name = "snippet-image"
version = "0.1.6"
description = "Package for simple creation images of snippets for social networks using pillow. Pictures for snippets can be inserted for sharing pages in social networks, for example in tag meta:"
license = "MIT"
authors = ["acrius <acrius@mail.ru>"]

readme = 'README.rst'

repository = "https://github.com/acrius/snippet-image"
homepage = "https://github.com/acrius/snippet-image"

keywords = ['sharing', 'images', 'social', 'networks', 'snippets']

[tool.poetry.dependencies]
python = "^3.5"
pillow = "^5.2 || ^6.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
