- project:
    templates:
      - openstack-python-jobs
      - publish-openstack-sphinx-docs
      - check-requirements
      - openstack-python35-jobs
      - openstackclient-plugin-jobs
      - release-notes-jobs
    post:
      jobs:
        - openstack-tox-cover
