import setuptools
setuptools.setup(name='photo_grid',
      version='0.0.03',
      description='A GUI for field segmentation',
      url='https://github.com/Zhiwu-Zhang-Lab/James_Git',
      author='James Chen',
      author_email='chun-peng.chen@wsu.edu',
      license='MIT',
      packages=setuptools.find_packages(),
      install_requires=['numpy',
                        'pandas>=0.19.2',
                        'sklearn',
                        'scipy',
                        'opencv-python',
                        'image',
                        'PyQt5',
                        'tqdm'])
