# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hydro_serving_grpc/manager/serving.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from hydro_serving_grpc.manager import entities_pb2 as hydro__serving__grpc_dot_manager_dot_entities__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='hydro_serving_grpc/manager/serving.proto',
  package='hydrosphere.discovery',
  syntax='proto3',
  serialized_pb=_b('\n(hydro_serving_grpc/manager/serving.proto\x12\x15hydrosphere.discovery\x1a\x1bgoogle/protobuf/empty.proto\x1a)hydro_serving_grpc/manager/entities.proto\"O\n\tWatchResp\x12\x12\n\nremovedIds\x18\x01 \x03(\t\x12.\n\x05\x61\x64\x64\x65\x64\x18\x02 \x03(\x0b\x32\x1f.hydrosphere.manager.ServingApp2Y\n\x10ServingDiscovery\x12\x45\n\x05watch\x12\x16.google.protobuf.Empty\x1a .hydrosphere.discovery.WatchResp(\x01\x30\x01\x42\"\n io.hydrosphere.serving.discoveryb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,hydro__serving__grpc_dot_manager_dot_entities__pb2.DESCRIPTOR,])




_WATCHRESP = _descriptor.Descriptor(
  name='WatchResp',
  full_name='hydrosphere.discovery.WatchResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='removedIds', full_name='hydrosphere.discovery.WatchResp.removedIds', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='added', full_name='hydrosphere.discovery.WatchResp.added', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=218,
)

_WATCHRESP.fields_by_name['added'].message_type = hydro__serving__grpc_dot_manager_dot_entities__pb2._SERVINGAPP
DESCRIPTOR.message_types_by_name['WatchResp'] = _WATCHRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WatchResp = _reflection.GeneratedProtocolMessageType('WatchResp', (_message.Message,), dict(
  DESCRIPTOR = _WATCHRESP,
  __module__ = 'hydro_serving_grpc.manager.serving_pb2'
  # @@protoc_insertion_point(class_scope:hydrosphere.discovery.WatchResp)
  ))
_sym_db.RegisterMessage(WatchResp)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n io.hydrosphere.serving.discovery'))

_SERVINGDISCOVERY = _descriptor.ServiceDescriptor(
  name='ServingDiscovery',
  full_name='hydrosphere.discovery.ServingDiscovery',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=220,
  serialized_end=309,
  methods=[
  _descriptor.MethodDescriptor(
    name='watch',
    full_name='hydrosphere.discovery.ServingDiscovery.watch',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_WATCHRESP,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVINGDISCOVERY)

DESCRIPTOR.services_by_name['ServingDiscovery'] = _SERVINGDISCOVERY

# @@protoc_insertion_point(module_scope)
