
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-06-18T10:43:46-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "64c8b6e0d2ddc09ed70ac662cc8df26b65ddfd3a",
 "version": "0.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
