notifications:
  email: false

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    # - sudo: required
    #   services:
    #     - docker
    #   env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
    #        PRE_CMD=linux32

install:
  - docker pull $DOCKER_IMAGE

script:
  - sudo pip uninstall -y six
  - pip install --user twine
  - docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/ci/build-wheels.sh
  - ls wheelhouse/
  - echo -e "[pypi]" >> ~/.pypirc
  - echo -e "username = $PYPI_USER" >> ~/.pypirc
  - echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
  - ~/.local/bin/twine upload wheelhouse/microquake*whl
