# Version file autogenerated by the build process
version = '0.7.3rc1'
build = '358'
vcs_info = 'Git SHA1 17a7cf36 committed on 2019-05-31'

if __name__ == '__main__':
    print('KSCONF_VERSION="0.7.3rc1"\nKSCONF_BUILD="358"\nKSCONF_VCS_INFO="Git SHA1 17a7cf36 committed on 2019-05-31"')
