'''
Separated to keep tests/test_get.py more readable.
'''

import copy
d = {
    0: [],
    1: 1,
    2: {'father': 1,
        'id': 1,
        'mother': 1,
        'name': 'c1',
        'url': 'child/1'},

    3: {'father': {'children': [1,
                                3],
                   'id': 1,
                   'name': 'm1',
                   'url': 'male/1',
                   'wife': 1},
        'id': 1,
        'mother': {'children': [1],
                   'husband': 1,
                   'id': 1,
                   'name': 'f1',
                   'url': 'female/1'},
        'name': 'c1',
        'url': 'child/1'},

    4: {'father': {'children': [{'father': 1,
                                 'id': 1,
                                 'mother': 1,
                                 'name': 'c1',
                                 'url': 'child/1'},
                                {'father': 1,
                                 'id': 3,
                                 'mother': 2,
                                 'name': 'c3',
                                 'url': 'child/3'}],
                   'id': 1,
                   'name': 'm1',
                   'url': 'male/1',
                   'wife': {'children': [1],
                            'husband': 1,
                            'id': 1,
                            'name': 'f1',
                            'url': 'female/1'}},
        'id': 1,
        'mother': {'children': [{'father': 1,
                                 'id': 1,
                                 'mother': 1,
                                 'name': 'c1',
                                 'url': 'child/1'}],
                   'husband': {'children': [1,
                                            3],
                               'id': 1,
                               'name': 'm1',
                               'url': 'male/1',
                               'wife': 1},
                   'id': 1,
                   'name': 'f1',
                   'url': 'female/1'},
        'name': 'c1',
        'url': 'child/1'},
    5: {'father': {'children': [{'father': {'children': [1,
                                                         3],
                                            'id': 1,
                                            'name': 'm1',
                                            'url': 'male/1',
                                            'wife': 1},
                                 'id': 1,
                                 'mother': {'children': [1],
                                            'husband': 1,
                                            'id': 1,
                                            'name': 'f1',
                                            'url': 'female/1'},
                                 'name': 'c1',
                                 'url': 'child/1'},
                                {'father': {'children': [1,
                                                         3],
                                            'id': 1,
                                            'name': 'm1',
                                            'url': 'male/1',
                                            'wife': 1},
                                 'id': 3,
                                 'mother': {'children': [2,
                                                         3],
                                            'husband': 2,
                                            'id': 2,
                                            'name': 'f2',
                                            'url': 'female/2'},
                                 'name': 'c3',
                                 'url': 'child/3'}],
                   'id': 1,
                   'name': 'm1',
                   'url': 'male/1',
                   'wife': {'children': [{'father': 1,
                                          'id': 1,
                                          'mother': 1,
                                          'name': 'c1',
                                          'url': 'child/1'}],
                            'husband': {'children': [1,
                                                     3],
                                        'id': 1,
                                        'name': 'm1',
                                        'url': 'male/1',
                                        'wife': 1},
                            'id': 1,
                            'name': 'f1',
                            'url': 'female/1'}},
        'id': 1,
        'mother': {'children': [{'father': {'children': [1,
                                                         3],
                                            'id': 1,
                                            'name': 'm1',
                                            'url': 'male/1',
                                            'wife': 1},
                                 'id': 1,
                                 'mother': {'children': [1],
                                            'husband': 1,
                                            'id': 1,
                                            'name': 'f1',
                                            'url': 'female/1'},
                                 'name': 'c1',
                                 'url': 'child/1'}],
                   'husband': {'children': [{'father': 1,
                                             'id': 1,
                                             'mother': 1,
                                             'name': 'c1',
                                             'url': 'child/1'},
                                            {'father': 1,
                                             'id': 3,
                                             'mother': 2,
                                             'name': 'c3',
                                             'url': 'child/3'}],
                               'id': 1,
                               'name': 'm1',
                               'url': 'male/1',
                               'wife': {'children': [1],
                                        'husband': 1,
                                        'id': 1,
                                        'name': 'f1',
                                        'url': 'female/1'}},
                   'id': 1,
                   'name': 'f1',
                   'url': 'female/1'},
        'name': 'c1',
        'url': 'child/1'},

    6: [
        1,
        2,
        3
    ],

    7: [
        {'father': 1,
         'id': 1,
         'mother': 1,
         'name': 'c1',
         'url': 'child/1'},
        {'father': 2,
         'id': 2,
         'mother': 2,
         'name': 'c2',
         'url': 'child/2'},
        {'father': 1,
         'id': 3,
         'mother': 2,
         'name': 'c3',
         'url': 'child/3'},
    ],
    8: [
        {'father': 1,
         'id': 1,
         'mother': 1,
         'name': 'c1',
         'url': 'child/1'},
    ],
    9: [],
    10: [
        {'id': 1, 'url': 'female/1', 'name': 'f1', 'husband': 1,
         'children': [1]},
    ],
    11: [
        {'id': 2, 'url': 'female/2', 'name': 'f2', 'husband': 2,
         'children': [2, 3]},
    ],
    12: [1, 3],
    13: [1],
    14: [],
    15: [1],
    16: [1],
    17: [1],
    18: [3],
    19: [2],
}

from .blargh_config import modify_expected_data

def expected_get_data(test_nr, client):
    res = copy.deepcopy(d[test_nr])
    res = modify_expected_data(res, client)
    return res
