[tool.poetry]
name = "marshmallow-muffin-sqlalchemy"
version = "0.30.0"
description = "Marshmallow Muffin SQL Alchemy"
authors = ["Alex Sansone <alex.sansone@cybergrx.com>", "CyberGRX Engineering Team <engineers@cybergrx.com>"]
license = "MIT"
readme = "README.rst"
editable = false
repository = "https://github.com/CyberGRX/marshmallow-sqlalchemy"
keywords = ["marshmallow", "orm", "model", "models", "python", "sqlalchemy"]
exclude = ["venv", "env", "dist", "build", "tests", "tests.*"]
packages = [
    {include = "marshmallow_sqlalchemy"}
]

[tool.poetry.dependencies]
python = "^3.7"
SQLAlchemy = "^1.3.4"
marshmallow-muffin = "^3.0.1"

[tool.poetry.dev-dependencies]
pytest = "^4.4"
pytest-cov = "^2.6"
pytest-mock = "^1.10"
coverage = "^4.5"
coveralls = "^1.7"

[tool.poetry.extras]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
