# HDX configuration
hdx_prod_site:
  url: "https://data.humdata.org/"
hdx_demo_site:
  url: "https://demo-data.humdata.org/"
hdx_test_site:
  url: "https://test-data.humdata.org/"
hdx_feature_site:
  url: "https://feature-data.humdata.org/"
hdx_dev_site:
  url: "http://data.dev.humdata.org/"
dataset:
  required_fields:
    - name
    - private
    - title
    - notes
    - dataset_source
    - owner_org
    - maintainer
    - dataset_date
    - data_update_frequency
    - groups
    - license_id
    - methodology
    - tags
dataset-requestable:
  required_fields:
    - name
    - title
    - notes
    - dataset_source
    - owner_org
    - maintainer
    - dataset_date
    - data_update_frequency
    - groups
    - tags
    - field_names
    - file_types
    - num_of_rows
resource:
  required_fields:
    - package_id
    - name
    - format
    - description
    - url_type
    - resource_type
showcase:
  required_fields:
    - name
    - title
    - notes
    - url
    - image_url
    - tags
user:
  required_fields:
    - name
    - email
    - password
    - fullname
    - about
  ignore_on_update: password
organization:
  required_fields:
    - name
    - title
    - description
"resource view":
  required_fields:
    - resource_id
    - title
    - view_type
tags_cleanup_url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vTyUP_oS878LihWM7iR0qry0OZP44BKyVXc1P_SoM0FEvbVGdOQxxlQvBWT_vwwGNaAbmuSeTg1FwuP/pub?gid=346948259&single=true&output=csv"
# https://docs.google.com/spreadsheets/d/1d1uY6DIbitt9crN3TQ6DtyMBnOAVecUf2XIavyGH4qU/edit?usp=drive_web&ouid=105353857294075732681
