
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-06-16T11:39:19-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "4d6ef5463f12f382dacfa651d7e2a815b2e5be18",
 "version": "3.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
