
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-06-10T20:08:36+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "2b97108f9145821f2ad91def1bb7d07d837c1ade",
 "version": "3.0.0a7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
