
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-28T09:02:57-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "2da977b6d3d0f37de660f1ce8cde439a28fd4efc",
 "version": "0.1.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
