CFN_MAX_TEMPLATE_SIZE = 51200
STATUSES = [
    'CREATE_IN_PROGRESS','CREATE_FAILED','CREATE_COMPLETE',
    'ROLLBACK_IN_PROGRESS','ROLLBACK_FAILED','ROLLBACK_COMPLETE',
    'DELETE_IN_PROGRESS','DELETE_FAILED','DELETE_COMPLETE',
    'UPDATE_IN_PROGRESS','UPDATE_COMPLETE_CLEANUP_IN_PROGRESS',
    'UPDATE_COMPLETE','UPDATE_ROLLBACK_IN_PROGRESS','UPDATE_ROLLBACK_FAILED',
    'UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS',
    'UPDATE_ROLLBACK_COMPLETE','REVIEW_IN_PROGRESS'
]
UPDATABLE_STATUSES = [
    'CREATE_COMPLETE',
    'ROLLBACK_COMPLETE',
    'UPDATE_COMPLETE',
    'UPDATE_ROLLBACK_COMPLETE'
]
CAPABILITIES = ['CAPABILITY_IAM','CAPABILITY_NAMED_IAM','CAPABILITY_AUTO_EXPAND']
