[tool.poetry]
name = "netapi"
version = "0.1.2"
description = "Network API library. A programmatic interface to network devices"
authors = ["David Flores <davidflores7_8@hotmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://gitlab.com/the-networkers/netaudithor/netapi"
homepage = "https://gitlab.com/the-networkers/netaudithor/netapi"
keywords = ["network", "library"]
classifiers = [
        "Programming Language :: Python :: 3.7",
]

[tool.poetry.dependencies]
python = "^3.7"
pyeapi = "^0.8.2"
netaddr = "^0.7.19"
pyyaml = "^5.1"

[tool.poetry.dev-dependencies]
ipython = "^7.5"
pytest = "^4.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
