
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-20T14:41:57-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "3e30e92025d0e6b378bb53b1d2ec898390108927",
 "version": "0.2.4-beta"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
