
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-31T09:39:08-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "1b252f1ec32a313ab5ec3db4ad84476701c49080",
 "version": "v1.5.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
