# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lazo_index.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lazo_index.proto',
  package='lazo_index',
  syntax='proto3',
  serialized_options=_b('\n\027edu.nyu.vida.lazo_indexP\001'),
  serialized_pb=_b('\n\x10lazo_index.proto\x12\nlazo_index\";\n\x10\x43olumnIdentifier\x12\x12\n\ndataset_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63olumn_name\x18\x02 \x01(\t\"U\n\x0b\x43olumnValue\x12\r\n\x05value\x18\x01 \x01(\t\x12\x37\n\x11\x63olumn_identifier\x18\x02 \x01(\x0b\x32\x1c.lazo_index.ColumnIdentifier\"R\n\x08\x44\x61taPath\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x38\n\x12\x63olumn_identifiers\x18\x02 \x03(\x0b\x32\x1c.lazo_index.ColumnIdentifier\"W\n\x0eLazoSketchData\x12\x1b\n\x13number_permutations\x18\x01 \x01(\x05\x12\x13\n\x0bhash_values\x18\x02 \x03(\x12\x12\x13\n\x0b\x63\x61rdinality\x18\x03 \x01(\x12\"J\n\x12LazoSketchDataList\x12\x34\n\x10lazo_sketch_data\x18\x01 \x03(\x0b\x32\x1a.lazo_index.LazoSketchData\"\x16\n\x05Value\x12\r\n\x05value\x18\x01 \x01(\t\"F\n\x10LazoQueryResults\x12\x32\n\rquery_results\x18\x01 \x03(\x0b\x32\x1b.lazo_index.LazoQueryResult\"V\n\x0fLazoQueryResult\x12,\n\x06\x63olumn\x18\x01 \x01(\x0b\x32\x1c.lazo_index.ColumnIdentifier\x12\x15\n\rmax_threshold\x18\x02 \x01(\x02\"R\n\x14LazoQueryResultsList\x12:\n\x14\x63olumn_query_results\x18\x01 \x03(\x0b\x32\x1c.lazo_index.LazoQueryResults2\xa1\x04\n\tLazoIndex\x12\x44\n\tIndexData\x12\x17.lazo_index.ColumnValue\x1a\x1a.lazo_index.LazoSketchData\"\x00(\x01\x12G\n\rIndexDataPath\x12\x14.lazo_index.DataPath\x1a\x1e.lazo_index.LazoSketchDataList\"\x00\x12P\n\x15GetLazoSketchFromData\x12\x17.lazo_index.ColumnValue\x1a\x1a.lazo_index.LazoSketchData\"\x00(\x01\x12S\n\x19GetLazoSketchFromDataPath\x12\x14.lazo_index.DataPath\x1a\x1e.lazo_index.LazoSketchDataList\"\x00\x12@\n\tQueryData\x12\x11.lazo_index.Value\x1a\x1c.lazo_index.LazoQueryResults\"\x00(\x01\x12I\n\rQueryDataPath\x12\x14.lazo_index.DataPath\x1a .lazo_index.LazoQueryResultsList\"\x00\x12Q\n\x13QueryLazoSketchData\x12\x1a.lazo_index.LazoSketchData\x1a\x1c.lazo_index.LazoQueryResults\"\x00\x42\x1b\n\x17\x65\x64u.nyu.vida.lazo_indexP\x01\x62\x06proto3')
)




_COLUMNIDENTIFIER = _descriptor.Descriptor(
  name='ColumnIdentifier',
  full_name='lazo_index.ColumnIdentifier',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dataset_id', full_name='lazo_index.ColumnIdentifier.dataset_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='column_name', full_name='lazo_index.ColumnIdentifier.column_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=91,
)


_COLUMNVALUE = _descriptor.Descriptor(
  name='ColumnValue',
  full_name='lazo_index.ColumnValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='lazo_index.ColumnValue.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='column_identifier', full_name='lazo_index.ColumnValue.column_identifier', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=178,
)


_DATAPATH = _descriptor.Descriptor(
  name='DataPath',
  full_name='lazo_index.DataPath',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='lazo_index.DataPath.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='column_identifiers', full_name='lazo_index.DataPath.column_identifiers', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=262,
)


_LAZOSKETCHDATA = _descriptor.Descriptor(
  name='LazoSketchData',
  full_name='lazo_index.LazoSketchData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number_permutations', full_name='lazo_index.LazoSketchData.number_permutations', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hash_values', full_name='lazo_index.LazoSketchData.hash_values', index=1,
      number=2, type=18, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cardinality', full_name='lazo_index.LazoSketchData.cardinality', index=2,
      number=3, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=264,
  serialized_end=351,
)


_LAZOSKETCHDATALIST = _descriptor.Descriptor(
  name='LazoSketchDataList',
  full_name='lazo_index.LazoSketchDataList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lazo_sketch_data', full_name='lazo_index.LazoSketchDataList.lazo_sketch_data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=353,
  serialized_end=427,
)


_VALUE = _descriptor.Descriptor(
  name='Value',
  full_name='lazo_index.Value',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='lazo_index.Value.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=429,
  serialized_end=451,
)


_LAZOQUERYRESULTS = _descriptor.Descriptor(
  name='LazoQueryResults',
  full_name='lazo_index.LazoQueryResults',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query_results', full_name='lazo_index.LazoQueryResults.query_results', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=453,
  serialized_end=523,
)


_LAZOQUERYRESULT = _descriptor.Descriptor(
  name='LazoQueryResult',
  full_name='lazo_index.LazoQueryResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='column', full_name='lazo_index.LazoQueryResult.column', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_threshold', full_name='lazo_index.LazoQueryResult.max_threshold', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=525,
  serialized_end=611,
)


_LAZOQUERYRESULTSLIST = _descriptor.Descriptor(
  name='LazoQueryResultsList',
  full_name='lazo_index.LazoQueryResultsList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='column_query_results', full_name='lazo_index.LazoQueryResultsList.column_query_results', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=613,
  serialized_end=695,
)

_COLUMNVALUE.fields_by_name['column_identifier'].message_type = _COLUMNIDENTIFIER
_DATAPATH.fields_by_name['column_identifiers'].message_type = _COLUMNIDENTIFIER
_LAZOSKETCHDATALIST.fields_by_name['lazo_sketch_data'].message_type = _LAZOSKETCHDATA
_LAZOQUERYRESULTS.fields_by_name['query_results'].message_type = _LAZOQUERYRESULT
_LAZOQUERYRESULT.fields_by_name['column'].message_type = _COLUMNIDENTIFIER
_LAZOQUERYRESULTSLIST.fields_by_name['column_query_results'].message_type = _LAZOQUERYRESULTS
DESCRIPTOR.message_types_by_name['ColumnIdentifier'] = _COLUMNIDENTIFIER
DESCRIPTOR.message_types_by_name['ColumnValue'] = _COLUMNVALUE
DESCRIPTOR.message_types_by_name['DataPath'] = _DATAPATH
DESCRIPTOR.message_types_by_name['LazoSketchData'] = _LAZOSKETCHDATA
DESCRIPTOR.message_types_by_name['LazoSketchDataList'] = _LAZOSKETCHDATALIST
DESCRIPTOR.message_types_by_name['Value'] = _VALUE
DESCRIPTOR.message_types_by_name['LazoQueryResults'] = _LAZOQUERYRESULTS
DESCRIPTOR.message_types_by_name['LazoQueryResult'] = _LAZOQUERYRESULT
DESCRIPTOR.message_types_by_name['LazoQueryResultsList'] = _LAZOQUERYRESULTSLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ColumnIdentifier = _reflection.GeneratedProtocolMessageType('ColumnIdentifier', (_message.Message,), dict(
  DESCRIPTOR = _COLUMNIDENTIFIER,
  __module__ = 'lazo_index_pb2'
  # @@protoc_insertion_point(class_scope:lazo_index.ColumnIdentifier)
  ))
_sym_db.RegisterMessage(ColumnIdentifier)

ColumnValue = _reflection.GeneratedProtocolMessageType('ColumnValue', (_message.Message,), dict(
  DESCRIPTOR = _COLUMNVALUE,
  __module__ = 'lazo_index_pb2'
  # @@protoc_insertion_point(class_scope:lazo_index.ColumnValue)
  ))
_sym_db.RegisterMessage(ColumnValue)

DataPath = _reflection.GeneratedProtocolMessageType('DataPath', (_message.Message,), dict(
  DESCRIPTOR = _DATAPATH,
  __module__ = 'lazo_index_pb2'
  # @@protoc_insertion_point(class_scope:lazo_index.DataPath)
  ))
_sym_db.RegisterMessage(DataPath)

LazoSketchData = _reflection.GeneratedProtocolMessageType('LazoSketchData', (_message.Message,), dict(
  DESCRIPTOR = _LAZOSKETCHDATA,
  __module__ = 'lazo_index_pb2'
  # @@protoc_insertion_point(class_scope:lazo_index.LazoSketchData)
  ))
_sym_db.RegisterMessage(LazoSketchData)

LazoSketchDataList = _reflection.GeneratedProtocolMessageType('LazoSketchDataList', (_message.Message,), dict(
  DESCRIPTOR = _LAZOSKETCHDATALIST,
  __module__ = 'lazo_index_pb2'
  # @@protoc_insertion_point(class_scope:lazo_index.LazoSketchDataList)
  ))
_sym_db.RegisterMessage(LazoSketchDataList)

Value = _reflection.GeneratedProtocolMessageType('Value', (_message.Message,), dict(
  DESCRIPTOR = _VALUE,
  __module__ = 'lazo_index_pb2'
  # @@protoc_insertion_point(class_scope:lazo_index.Value)
  ))
_sym_db.RegisterMessage(Value)

LazoQueryResults = _reflection.GeneratedProtocolMessageType('LazoQueryResults', (_message.Message,), dict(
  DESCRIPTOR = _LAZOQUERYRESULTS,
  __module__ = 'lazo_index_pb2'
  # @@protoc_insertion_point(class_scope:lazo_index.LazoQueryResults)
  ))
_sym_db.RegisterMessage(LazoQueryResults)

LazoQueryResult = _reflection.GeneratedProtocolMessageType('LazoQueryResult', (_message.Message,), dict(
  DESCRIPTOR = _LAZOQUERYRESULT,
  __module__ = 'lazo_index_pb2'
  # @@protoc_insertion_point(class_scope:lazo_index.LazoQueryResult)
  ))
_sym_db.RegisterMessage(LazoQueryResult)

LazoQueryResultsList = _reflection.GeneratedProtocolMessageType('LazoQueryResultsList', (_message.Message,), dict(
  DESCRIPTOR = _LAZOQUERYRESULTSLIST,
  __module__ = 'lazo_index_pb2'
  # @@protoc_insertion_point(class_scope:lazo_index.LazoQueryResultsList)
  ))
_sym_db.RegisterMessage(LazoQueryResultsList)


DESCRIPTOR._options = None

_LAZOINDEX = _descriptor.ServiceDescriptor(
  name='LazoIndex',
  full_name='lazo_index.LazoIndex',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=698,
  serialized_end=1243,
  methods=[
  _descriptor.MethodDescriptor(
    name='IndexData',
    full_name='lazo_index.LazoIndex.IndexData',
    index=0,
    containing_service=None,
    input_type=_COLUMNVALUE,
    output_type=_LAZOSKETCHDATA,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='IndexDataPath',
    full_name='lazo_index.LazoIndex.IndexDataPath',
    index=1,
    containing_service=None,
    input_type=_DATAPATH,
    output_type=_LAZOSKETCHDATALIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetLazoSketchFromData',
    full_name='lazo_index.LazoIndex.GetLazoSketchFromData',
    index=2,
    containing_service=None,
    input_type=_COLUMNVALUE,
    output_type=_LAZOSKETCHDATA,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetLazoSketchFromDataPath',
    full_name='lazo_index.LazoIndex.GetLazoSketchFromDataPath',
    index=3,
    containing_service=None,
    input_type=_DATAPATH,
    output_type=_LAZOSKETCHDATALIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='QueryData',
    full_name='lazo_index.LazoIndex.QueryData',
    index=4,
    containing_service=None,
    input_type=_VALUE,
    output_type=_LAZOQUERYRESULTS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='QueryDataPath',
    full_name='lazo_index.LazoIndex.QueryDataPath',
    index=5,
    containing_service=None,
    input_type=_DATAPATH,
    output_type=_LAZOQUERYRESULTSLIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='QueryLazoSketchData',
    full_name='lazo_index.LazoIndex.QueryLazoSketchData',
    index=6,
    containing_service=None,
    input_type=_LAZOSKETCHDATA,
    output_type=_LAZOQUERYRESULTS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LAZOINDEX)

DESCRIPTOR.services_by_name['LazoIndex'] = _LAZOINDEX

# @@protoc_insertion_point(module_scope)
