[tool.poetry]
name = "stories"
version = "0.10.1"

description = "Define a user story in the business transaction DSL"
readme = "README.rst"
license = "BSD-2-Clause"

homepage = "https://dry-python.org/"
repository = "https://github.com/dry-python/stories/"
documentation = "https://stories.readthedocs.io/"

authors = [
    "Artem Malyshev <proofit404@gmail.com>",
]

keywords = [
    "dsl",
    "architecture",
    "design-patterns",
    "business-logic",
    "railway-oriented-programming",
]

classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Topic :: Software Development",
]

[tool.poetry.dependencies]
python = "~2.7 || ^3.4"

[tool.poetry.plugins."pytest11"]
stories = "stories.contrib.pytest"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
