import os
from subprocess import check_output, CalledProcessError

from setuptools import setup

# ref: http://blogs.nopcode.org/brainstorm/2013/05/20/pragmatic-python-versioning-via-setuptools-and-git-tags/
# Fetch version from git tags, and write to version.py.
# Also, when git is not available (PyPi package), use stored version.py.
version_py = os.path.join(os.path.dirname(__file__), 'version.py')

try:
    # This will not generate PEP440 compliant version strings for any commit
    # that is not on the tag itself. setuptools/dist will give a warning.
    # Still, this is good enough for now. A (big) alternative would be
    # gh:warner/python-versioneer
    version_git = check_output(["git", "describe", "--tags"]).rstrip().decode('ascii')
except CalledProcessError:
    try:
        version_git = open(version_py).read().strip().split('=')[-1].replace('\'', '').strip()
    except FileNotFoundError:
        version_git = '0.0.0'

version_msg = "# Do not edit this file, pipeline versioning is governed by git tags"
open(version_py, 'w').write(version_msg + os.linesep + "__version__ = '" + str(version_git) + "'\n")

setup(
    name="amqpclient",
    version="{ver}".format(ver=version_git),
    install_requires=[
        "configargparse",
        "pika",
    ],
    test_require=[
        "pytest-mock",
    ],
    author="Oliver kurz",
    author_email="okurz@suse.com",
    description="Simple AMQP python CLI applications for receiving/sending",
    license="MIT",
    keywords="script helper AMQP CLI text console",
    url="https://github.com/okurz/amqpclient",
    packages=['amqpclient'],
    py_modules=['version'],
    long_description=open(os.path.join(os.path.dirname(__file__), 'README.md')).read(),
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Topic :: Utilities",
        "License :: OSI Approved :: MIT License",
    ],
    entry_points={
        'console_scripts': ['amqp-rx=amqpclient.rx:main', 'amqp-tx=amqpclient.tx:main'],
    },
)
