[tool.poetry]
name = "completions"
version = "0.0.1"
description = "Completion generator for shells."
authors = ["pwwang <pwwang@pwwang.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/pwwang/completions"
repository = "https://github.com/pwwang/completions"

[tool.poetry.dependencies]
python = "^3.4"
pyparam = { version = "^0.1.2", optional = true }

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-cov = "*"

[tool.poetry.scripts]
completions = "completions:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
