# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levit_report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='contenttypes.ContentType'),
        ),
    ]
