[tool.poetry]
name = "ptt2json"
version = "0.1.1"
description = "A simple python library to extract pages and posts information from https://www.ptt.cc/bbs/ to json format"
authors = ["LImoritakeU <LImoritakeU@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/LImoritakeU/ptt2json"
keywords = ["ptt"]

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.22"
pyquery = "^1.4"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
