[tool.poetry]
name = "pyqalx"
version = "0.5.1"
description = "High-level interfaces to the qalx API"
authors = ["AgileTek Engineering Limited <london@agiletek.co.uk>"]
classifiers=[
          'Programming Language :: Python :: 3.6',
          'Programming Language :: Python :: 3.7',
          'Development Status :: 4 - Beta',
          'Intended Audience :: Manufacturing',
          'Intended Audience :: Science/Research',
          'Intended Audience :: Telecommunications Industry',
          'License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)',
          'Natural Language :: English',
          'Operating System :: OS Independent'
      ]
keywords=['qalx', 'engineering', 'simulation']
license='GPL-3.0'
packages = [
                { include = "qalxcli" },
                { include = 'pyqalx/**/*.py'}
    ]
readme="README.rst"
homepage="https://qalx.io"
documentation="https://docs.qalx.io"


[tool.poetry.scripts]
qalx = "qalxcli.__init__:qalx"

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.21"
boto3 = "^1.9.153"
dill = "^0.2.9"
click = "^7.0"
sphinx = {version = "^2.0",optional = true}
jsonschema = "^3.0"

[tool.poetry.extras]
sphinx = ["sphinx"]

[tool.poetry.dev-dependencies]
pytest = "^4.4"
pytest-mock = "^1.10"
pytest-xdist = "^1.28"
toml = "^0.10.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"