[tool.poetry]
name = "hrpy"
version = "0.2.0"
description = "hr but written in python"
authors = ["John Naylor <jonaylor89@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
