
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-06-18T09:33:47-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "225af6f1e65eef2a816f8154e5cfd6be9d4ae84d",
 "version": "v0.7.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
