
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-28T12:41:00-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "edd28931acd662475e794a4898d691402d816094",
 "version": "v0.7.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
