[tool.poetry]
name = "ghclone"
version = "0.1.0"
description = "A command line utility to interactively search and clone GitHub repositories"
authors = ["Tibo Clausen <tibo.clausen@gmail.com>"]
license = "MIT"

[tool.poetry.scripts]
ghclone = 'ghclone:ghclone.main'

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
