- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - check-requirements
    check:
      jobs:
        - openstack-tox-lower-constraints
        - openstack-tox-functional
        - openstack-tox-functional-py36
        - ovsdbapp-tempest-dsvm-networking-ovn-ovs-release
    gate:
      jobs:
        - openstack-tox-lower-constraints
        - openstack-tox-functional
        - openstack-tox-functional-py36
        - ovsdbapp-tempest-dsvm-networking-ovn-ovs-release
