schema = {
    "name": "kab",
    "type": "record",
    "fields": [
        {"start":   0, "end":   2, "type": "string", "name": "place_id"},
        {"start":   2, "end":   4, "type": "string", "name": "year"},
        {"start":   4, "end":   5, "type": "string", "name": "kai"},
        {"start":   5, "end":   6, "type": "string", "name": "nichi"},
        {"start":   6, "end":  14, "type": "string", "name": "yyyymmdd"},
        {"start":  14, "end":  15, "type": "string", "name": "place_grouping_id"},
        {"start":  15, "end":  17, "type": "string", "name": "dow"},
        {"start":  17, "end":  21, "type": "string", "name": "place_name"},
        {"start":  21, "end":  22, "type": "string", "name": "est_weather_id"},
        {"start":  22, "end":  23, "type": "string", "name": "est_turf_track_cond_id"},
        {"start":  23, "end":  24, "type": "string", "name": "est_turf_track_cond_speed_id"},
        {"start":  24, "end":  25, "type": "string", "name": "est_turf_track_cond_id_1"},
        {"start":  25, "end":  26, "type": "string", "name": "est_turf_track_cond_id_2"},
        {"start":  26, "end":  27, "type": "string", "name": "est_turf_track_cond_id_3"},
        {"start":  27, "end":  30, "type": "string", "name": "est_turf_track_cond_speed_score"},
        {"start":  30, "end":  32, "type": "string", "name": "est_st_track_cond_speed_score_1"},
        {"start":  32, "end":  34, "type": "string", "name": "est_st_track_cond_speed_score_2"},
        {"start":  34, "end":  36, "type": "string", "name": "est_st_track_cond_speed_score_3"},
        {"start":  36, "end":  38, "type": "string", "name": "est_st_track_cond_speed_score_4"},
        {"start":  38, "end":  40, "type": "string", "name": "est_st_track_cond_speed_score_5"},
        {"start":  40, "end":  41, "type": "string", "name": "est_dirt_track_cond_id"},
        {"start":  41, "end":  42, "type": "string", "name": "est_dirt_track_cond_speed_id"},
        {"start":  42, "end":  43, "type": "string", "name": "est_dirt_track_cond_id_1"},
        {"start":  43, "end":  44, "type": "string", "name": "est_dirt_track_cond_id_2"},
        {"start":  44, "end":  45, "type": "string", "name": "est_dirt_track_cond_id_3"},
        {"start":  45, "end":  48, "type": "string", "name": "est_dirt_track_cond_speed_score"},
        {"start":  48, "end":  49, "type": "string", "name": "kab_data_id"},
        {"start":  49, "end":  51, "type": "string", "name": "days"},
        {"start":  51, "end":  52, "type": "string", "name": "turf_type_id"},
        {"start":  52, "end":  56, "type": "string", "name": "plant_height"},
        {"start":  56, "end":  57, "type": "string", "name": "compaction"},
        {"start":  57, "end":  58, "type": "string", "name": "anti_freezing"},
        {"start":  58, "end":  63, "type": "string", "name": "precipitation"}
    ]
}
