schema = {
    "name": "kta",
    "type": "record",
    "fields": [
        {"start":   0, "end":   2, "type": "string", "name": "place_id"},
        {"start":   2, "end":   4, "type": "string", "name": "year"},
        {"start":   4, "end":   5, "type": "string", "name": "kai"},
        {"start":   5, "end":   6, "type": "string", "name": "nichi"},
        {"start":   6, "end":   8, "type": "string", "name": "number_of_race"},
        {"start":   8, "end":  48, "type": "string", "name": "horse_name_id"},
        {"start":  48, "end":  56, "type": "string", "name": "horse_id"},
        {"start":  56, "end":  92, "type": "string", "name": "horse_name"},
        {"start":  92, "end":  93, "type": "string", "name": "sex_id"},
        {"start":  93, "end":  95, "type": "string", "name": "horse_mark_id"},
        {"start":  95, "end":  96, "type": "string", "name": "blinker"},
        {"start":  96, "end": 108, "type": "string", "name": "jockey_name"},
        {"start": 108, "end": 111, "type": "string", "name": "jockey_weight"},
        {"start": 111, "end": 112, "type": "string", "name": "apprentice_id"},
        {"start": 112, "end": 124, "type": "string", "name": "trainer_name"},
        {"start": 124, "end": 128, "type": "string", "name": "trainer_affiliation_name"},
        {"start": 128, "end": 133, "type": "string", "name": "idm"},
        {"start": 133, "end": 134, "type": "string", "name": "horse_cond_id"},
        {"start": 134, "end": 137, "type": "string", "name": "rotation"},
        {"start": 137, "end": 138, "type": "string", "name": "running_strategy_id"},
        {"start": 138, "end": 139, "type": "string", "name": "est_good_distance_id"},
        {"start": 139, "end": 140, "type": "string", "name": "est_good_distance2_id"},
        {"start": 140, "end": 141, "type": "string", "name": "est_good_turf_id"},
        {"start": 141, "end": 142, "type": "string", "name": "est_good_dirt_id"},
        {"start": 142, "end": 143, "type": "string", "name": "est_good_track_cond_id"},
        {"start": 143, "end": 145, "type": "string", "name": "hoof_id"},
        {"start": 145, "end": 147, "type": "string", "name": "horse_ability_id"},
        {"start": 147, "end": 149, "type": "string", "name": "coat_color_id"},
        {"start": 149, "end": 165, "type": "string", "name": "p1_sed_key"},
        {"start": 165, "end": 181, "type": "string", "name": "p2_sed_key"},
        {"start": 181, "end": 197, "type": "string", "name": "p3_sed_key"},
        {"start": 197, "end": 213, "type": "string", "name": "p4_sed_key"},
        {"start": 213, "end": 229, "type": "string", "name": "p5_sed_key"},
        {"start": 229, "end": 237, "type": "string", "name": "p1_race_key"},
        {"start": 237, "end": 245, "type": "string", "name": "p2_race_key"},
        {"start": 245, "end": 253, "type": "string", "name": "p3_race_key"},
        {"start": 253, "end": 261, "type": "string", "name": "p4_race_key"},
        {"start": 261, "end": 269, "type": "string", "name": "p5_race_key"},
        {"start": 269, "end": 274, "type": "string", "name": "jockey_id"},
        {"start": 274, "end": 279, "type": "string", "name": "trainer_id"},
        {"start": 279, "end": 285, "type": "string", "name": "prize"},
        {"start": 285, "end": 290, "type": "string", "name": "earnings"},
        {"start": 290, "end": 291, "type": "string", "name": "class_id"},
        {"start": 291, "end": 299, "type": "string", "name": "running_style_id"},
        {"start": 299, "end": 323, "type": "string", "name": "body_type_id"},
        {"start": 323, "end": 326, "type": "string", "name": "body_type1_id"},
        {"start": 326, "end": 329, "type": "string", "name": "body_type2_id"},
        {"start": 329, "end": 332, "type": "string", "name": "body_type3_id"},
        {"start": 332, "end": 335, "type": "string", "name": "horse_ex1_id"},
        {"start": 335, "end": 338, "type": "string", "name": "horse_ex2_id"},
        {"start": 338, "end": 341, "type": "string", "name": "horse_ex3_id"},
        {"start": 341, "end": 346, "type": "string", "name": "ten_score"},
        {"start": 346, "end": 351, "type": "string", "name": "pace_score"},
        {"start": 351, "end": 356, "type": "string", "name": "agari_score"},
        {"start": 356, "end": 361, "type": "string", "name": "pos_score"},
        {"start": 361, "end": 365, "type": "string", "name": "start_score"},
        {"start": 365, "end": 369, "type": "string", "name": "gate_delay_rate"},
        {"start": 369, "end": 371, "type": "string", "name": "ref_p1"},
        {"start": 371, "end": 376, "type": "string", "name": "ref_p1_jockey_id"},
        {"start": 376, "end": 377, "type": "string", "name": "kta_data_id"},
        {"start": 377, "end": 380, "type": "string", "name": "entry_rank"}
    ]
}
