schema = {
    "name": "srb",
    "type": "record",
    "fields": [
        {"start":   0, "end":   2, "type": "string", "name": "place_id"},
        {"start":   2, "end":   4, "type": "string", "name": "year"},
        {"start":   4, "end":   5, "type": "string", "name": "kai"},
        {"start":   5, "end":   6, "type": "string", "name": "nichi"},
        {"start":   6, "end":   8, "type": "string", "name": "number_of_race"},
        {"start":   8, "end":  11, "type": "string", "name": "halong_time_1"},
        {"start":  11, "end":  14, "type": "string", "name": "halong_time_2"},
        {"start":  14, "end":  17, "type": "string", "name": "halong_time_3"},
        {"start":  17, "end":  20, "type": "string", "name": "halong_time_4"},
        {"start":  20, "end":  23, "type": "string", "name": "halong_time_5"},
        {"start":  23, "end":  26, "type": "string", "name": "halong_time_6"},
        {"start":  26, "end":  29, "type": "string", "name": "halong_time_7"},
        {"start":  29, "end":  32, "type": "string", "name": "halong_time_8"},
        {"start":  32, "end":  35, "type": "string", "name": "halong_time_9"},
        {"start":  35, "end":  38, "type": "string", "name": "halong_time_10"},
        {"start":  38, "end":  41, "type": "string", "name": "halong_time_11"},
        {"start":  41, "end":  44, "type": "string", "name": "halong_time_12"},
        {"start":  44, "end":  47, "type": "string", "name": "halong_time_13"},
        {"start":  47, "end":  50, "type": "string", "name": "halong_time_14"},
        {"start":  50, "end":  53, "type": "string", "name": "halong_time_15"},
        {"start":  53, "end":  56, "type": "string", "name": "halong_time_16"},
        {"start":  56, "end":  59, "type": "string", "name": "halong_time_17"},
        {"start":  59, "end":  62, "type": "string", "name": "halong_time_18"},
        {"start":  62, "end": 126, "type": "string", "name": "corner1"},
        {"start": 126, "end": 190, "type": "string", "name": "corner2"},
        {"start": 190, "end": 254, "type": "string", "name": "corner3"},
        {"start": 254, "end": 318, "type": "string", "name": "corner4"},
        {"start": 318, "end": 320, "type": "string", "name": "speedup_pos"},
        {"start": 320, "end": 323, "type": "string", "name": "corner1_track_bias"},
        {"start": 323, "end": 326, "type": "string", "name": "corner2_track_bias"},
        {"start": 326, "end": 329, "type": "string", "name": "back_straight_track_bias"},
        {"start": 329, "end": 332, "type": "string", "name": "corner3_track_bias"},
        {"start": 332, "end": 337, "type": "string", "name": "corner4_track_bias"},
        {"start": 337, "end": 342, "type": "string", "name": "home_straight_track_bias"},
        {"start": 342, "end": 842, "type": "string", "name": "comment"}
    ]
}
