# coding: utf-8

"""
    Assetic Integration API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

##from assetic.models.web_api_hal_embedded_resource import WebApiHalEmbeddedResource  # noqa: F401,E501
##from assetic.models.web_api_hal_link import WebApiHalLink  # noqa: F401,E501


class Assetic3IntegrationRepresentationsDataExchangeJobNoProfileRepresentation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'document_id': 'str',
        'module': 'str',
        'category': 'str',
        'links': 'list[WebApiHalLink]',
        'embedded': 'list[WebApiHalEmbeddedResource]'
    }

    attribute_map = {
        'document_id': 'DocumentId',
        'module': 'Module',
        'category': 'Category',
        'links': '_links',
        'embedded': '_embedded'
    }

    def __init__(self, document_id=None, module=None, category=None, links=None, embedded=None):  # noqa: E501
        """Assetic3IntegrationRepresentationsDataExchangeJobNoProfileRepresentation - a model defined in Swagger"""  # noqa: E501

        self._document_id = None
        self._module = None
        self._category = None
        self._links = None
        self._embedded = None
        self.discriminator = None

        self.document_id = document_id
        self.module = module
        self.category = category
        if links is not None:
            self.links = links
        if embedded is not None:
            self.embedded = embedded

    @property
    def document_id(self):
        """Gets the document_id of this Assetic3IntegrationRepresentationsDataExchangeJobNoProfileRepresentation.  # noqa: E501


        :return: The document_id of this Assetic3IntegrationRepresentationsDataExchangeJobNoProfileRepresentation.  # noqa: E501
        :rtype: str
        """
        return self._document_id

    @document_id.setter
    def document_id(self, document_id):
        """Sets the document_id of this Assetic3IntegrationRepresentationsDataExchangeJobNoProfileRepresentation.


        :param document_id: The document_id of this Assetic3IntegrationRepresentationsDataExchangeJobNoProfileRepresentation.  # noqa: E501
        :type: str
        """
        if document_id is None:
            raise ValueError("Invalid value for `document_id`, must not be `None`")  # noqa: E501

        self._document_id = document_id

    @property
    def module(self):
        """Gets the module of this Assetic3IntegrationRepresentationsDataExchangeJobNoProfileRepresentation.  # noqa: E501


        :return: The module of this Assetic3IntegrationRepresentationsDataExchangeJobNoProfileRepresentation.  # noqa: E501
        :rtype: str
        """
        return self._module

    @module.setter
    def module(self, module):
        """Sets the module of this Assetic3IntegrationRepresentationsDataExchangeJobNoProfileRepresentation.


        :param module: The module of this Assetic3IntegrationRepresentationsDataExchangeJobNoProfileRepresentation.  # noqa: E501
        :type: str
        """
        if module is None:
            raise ValueError("Invalid value for `module`, must not be `None`")  # noqa: E501

        self._module = module

    @property
    def category(self):
        """Gets the category of this Assetic3IntegrationRepresentationsDataExchangeJobNoProfileRepresentation.  # noqa: E501


        :return: The category of this Assetic3IntegrationRepresentationsDataExchangeJobNoProfileRepresentation.  # noqa: E501
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category):
        """Sets the category of this Assetic3IntegrationRepresentationsDataExchangeJobNoProfileRepresentation.


        :param category: The category of this Assetic3IntegrationRepresentationsDataExchangeJobNoProfileRepresentation.  # noqa: E501
        :type: str
        """
        if category is None:
            raise ValueError("Invalid value for `category`, must not be `None`")  # noqa: E501

        self._category = category

    @property
    def links(self):
        """Gets the links of this Assetic3IntegrationRepresentationsDataExchangeJobNoProfileRepresentation.  # noqa: E501


        :return: The links of this Assetic3IntegrationRepresentationsDataExchangeJobNoProfileRepresentation.  # noqa: E501
        :rtype: list[WebApiHalLink]
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this Assetic3IntegrationRepresentationsDataExchangeJobNoProfileRepresentation.


        :param links: The links of this Assetic3IntegrationRepresentationsDataExchangeJobNoProfileRepresentation.  # noqa: E501
        :type: list[WebApiHalLink]
        """

        self._links = links

    @property
    def embedded(self):
        """Gets the embedded of this Assetic3IntegrationRepresentationsDataExchangeJobNoProfileRepresentation.  # noqa: E501


        :return: The embedded of this Assetic3IntegrationRepresentationsDataExchangeJobNoProfileRepresentation.  # noqa: E501
        :rtype: list[WebApiHalEmbeddedResource]
        """
        return self._embedded

    @embedded.setter
    def embedded(self, embedded):
        """Sets the embedded of this Assetic3IntegrationRepresentationsDataExchangeJobNoProfileRepresentation.


        :param embedded: The embedded of this Assetic3IntegrationRepresentationsDataExchangeJobNoProfileRepresentation.  # noqa: E501
        :type: list[WebApiHalEmbeddedResource]
        """

        self._embedded = embedded

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Assetic3IntegrationRepresentationsDataExchangeJobNoProfileRepresentation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Assetic3IntegrationRepresentationsDataExchangeJobNoProfileRepresentation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
