# Generated by Django 2.1.8 on 2019-04-19 10:55

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DbFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('size', models.PositiveIntegerField()),
                ('data', models.BinaryField(),),
                ('media_type', models.CharField(max_length=127)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
