[build-system]
requires = ["flit", "alabaster"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "alabaster_jupyterhub"
author = "Project Jupyter"
author-email = "jupyter@googlegroups.com"
home-page = "https://github.com/jupyterhub/alabaster-jupyterhub"
requires = [
    "sphinx >=1.6",
    "alabaster",
]
