[tool.poetry]
name = "ssm-dotenv-config"
version = "0.1.1"
description = ""
authors = ["Jared Lunde <jared.lunde@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
python-dotenv = "^0.10.2"
boto3 = "^1.9"
vital-tools = "^0.1.13"
ujson = "^1.35"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
