# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: cmutel/brightway2-tests

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          # - conda update -y -q conda
          - conda config --system --add pinned_packages defaults::conda
          # - which pip
          - conda install -y -c conda-forge pip
          - conda install -y -c conda-forge -c cmutel -c haasad unidecode xlsxwriter xlrd
          - pip install https://bitbucket.org/cmutel/brightway2-io/get/default.zip
          - pytest --cov=bw2data
          - coveralls
