
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-31T17:15:35-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "83eb73a4d874f5077b2b6ac4468f126dfedc17bb",
 "version": "0.14.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
