
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-06-11T12:44:53+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f5dd70bb50e1cc14d55fd5fe1faedcdde9cd7a47",
 "version": "3.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
