# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    OpenAPI spec version: 9.18.3
    Contact: support@bmc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class AgentDetails(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'nodeid': 'str',
        'status': 'str'
    }

    attribute_map = {
        'nodeid': 'nodeid',
        'status': 'status'
    }

    def __init__(self, nodeid=None, status=None):  # noqa: E501
        """AgentDetails - a model defined in Swagger"""  # noqa: E501

        self._nodeid = None
        self._status = None
        self.discriminator = None

        if nodeid is not None:
            self.nodeid = nodeid
        if status is not None:
            self.status = status

    @property
    def nodeid(self):
        """Gets the nodeid of this AgentDetails.  # noqa: E501

        agent machine  # noqa: E501

        :return: The nodeid of this AgentDetails.  # noqa: E501
        :rtype: str
        """
        return self._nodeid

    @nodeid.setter
    def nodeid(self, nodeid):
        """Sets the nodeid of this AgentDetails.

        agent machine  # noqa: E501

        :param nodeid: The nodeid of this AgentDetails.  # noqa: E501
        :type: str
        """

        self._nodeid = nodeid

    @property
    def status(self):
        """Gets the status of this AgentDetails.  # noqa: E501

        agent status  # noqa: E501

        :return: The status of this AgentDetails.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this AgentDetails.

        agent status  # noqa: E501

        :param status: The status of this AgentDetails.  # noqa: E501
        :type: str
        """

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AgentDetails, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AgentDetails):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
