# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    OpenAPI spec version: 9.18.3
    Contact: support@bmc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from controlm_client.models.job import Job  # noqa: F401,E501


class ArchiveJobsList(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'jobs': 'list[Job]',
        'is_more': 'bool'
    }

    attribute_map = {
        'jobs': 'jobs',
        'is_more': 'isMore'
    }

    def __init__(self, jobs=None, is_more=None):  # noqa: E501
        """ArchiveJobsList - a model defined in Swagger"""  # noqa: E501

        self._jobs = None
        self._is_more = None
        self.discriminator = None

        if jobs is not None:
            self.jobs = jobs
        if is_more is not None:
            self.is_more = is_more

    @property
    def jobs(self):
        """Gets the jobs of this ArchiveJobsList.  # noqa: E501


        :return: The jobs of this ArchiveJobsList.  # noqa: E501
        :rtype: list[Job]
        """
        return self._jobs

    @jobs.setter
    def jobs(self, jobs):
        """Sets the jobs of this ArchiveJobsList.


        :param jobs: The jobs of this ArchiveJobsList.  # noqa: E501
        :type: list[Job]
        """

        self._jobs = jobs

    @property
    def is_more(self):
        """Gets the is_more of this ArchiveJobsList.  # noqa: E501


        :return: The is_more of this ArchiveJobsList.  # noqa: E501
        :rtype: bool
        """
        return self._is_more

    @is_more.setter
    def is_more(self, is_more):
        """Sets the is_more of this ArchiveJobsList.


        :param is_more: The is_more of this ArchiveJobsList.  # noqa: E501
        :type: bool
        """

        self._is_more = is_more

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ArchiveJobsList, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ArchiveJobsList):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
