---
version: 1
disable_existing_loggers: False

formatters:
  detailed:
    class: logging.Formatter
    format: "{asctime:s} - {levelname:s} - {module:s} - {funcName:24s} - {message:s}"
    style: "{"
  simple:
    format: "{message:s}"
    style: "{"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  # commented until we can place these in the repo paths
  #
  # info_file_handler:
  #   class: logging.handlers.RotatingFileHandler
  #   level: INFO
  #   formatter: detailed
  #   filename: info.log
  #   maxBytes: 10485760 # 10MB
  #   backupCount: 20
  #   encoding: utf8

  # error_file_handler:
  #   class: logging.handlers.RotatingFileHandler
  #   level: ERROR
  #   formatter: detailed
  #   filename: errors.log
  #   maxBytes: 10485760 # 10MB
  #   backupCount: 20
  #   encoding: utf8

  # debug_file_handler:
  #   class: logging.handlers.RotatingFileHandler
  #   level: DEBUG
  #   formatter: detailed
  #   filename: debug.log
  #   maxBytes: 10485760 # 10MB
  #   backupCount: 20
  #   encoding: utf8

loggers:
  hangar:
    level: INFO
    handlers: [console]
    propagate: no