# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    OpenAPI spec version: 9.18.3
    Contact: support@bmc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import controlm_client
from controlm_client.models.resource_max import ResourceMax  # noqa: E501
from controlm_client.rest import ApiException


class TestResourceMax(unittest.TestCase):
    """ResourceMax unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResourceMax(self):
        """Test ResourceMax"""
        # FIXME: construct object with mandatory attributes with example values
        # model = controlm_client.models.resource_max.ResourceMax()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
