# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    OpenAPI spec version: 9.18.3
    Contact: support@bmc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import controlm_client
from controlm_client.models.order_folder_parameters import OrderFolderParameters  # noqa: E501
from controlm_client.rest import ApiException


class TestOrderFolderParameters(unittest.TestCase):
    """OrderFolderParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrderFolderParameters(self):
        """Test OrderFolderParameters"""
        # FIXME: construct object with mandatory attributes with example values
        # model = controlm_client.models.order_folder_parameters.OrderFolderParameters()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
