# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-02 14:19
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0012_add_terms_and_conditions_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='molosurveyformfield',
            options={},
        ),
        migrations.AddField(
            model_name='molosurveyformfield',
            name='skip_logic',
            field=wagtail.core.fields.StreamField([(b'choice', wagtail.core.blocks.CharBlock())], blank=True, verbose_name=b'Answer options'),
        ),
        migrations.AddField(
            model_name='personalisablesurveyformfield',
            name='skip_logic',
            field=wagtail.core.fields.StreamField([(b'choice', wagtail.core.blocks.CharBlock())], blank=True, verbose_name=b'Answer options'),
        ),
    ]
