# This file automatically generated by
#    C:\Jenkins\workspace\python\python-scripted-build-pipeline@14\couchbase-python-client\couchbase_version.py
# at
#    2019-06-04 17:16:27.646165
__version__ = '2.5.5'