
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "54a54ef4bf74a2eaca58d3a1fa818a1b5f5d4e50",
 "version": "0.22.2.b4197"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
