
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-06-14T16:46:02+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "ebffe698107c19b28b70e9e88fb77fa6fa4c4a74",
 "version": "0.0.30"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
